### ISSUE TITLE
minor-bug: Error with colors in past

### ISSUE THREAD

**Issue by aronwolf90** [ClickerMonkey/dayspan-vuetify#100]
When a event is in the past and you use css color words, then a crash happen.
E.g:
```
    events: [
      {
        data: {
          title: 'Test',
          color: 'red'     
        },
        schedule: {
          times: [9],
          duration: 30,        
          durationUnit: 'minutes',        
          month: [Month.OCTOBER],         
          dayOfMonth: [21]     
        }
      }
    ]
```

posible sulution: 
- just add a warning to the console

If you want, then I can make a pull request for this

**Comment by ClickerMonkey** [comment]
Color must be \#000000 - various functions need to parse it to compute colors to use in past, dragging, etc. I don't think it's worth the extra code to accept css color words - sorry!

**Comment by aronwolf90** [comment]
I does not mean a new code to accept it. What I mean is a warning that it does not work. I had to rad the source code to see what was the problem

**Comment by aronwolf90** [comment]
somethin like `Console.warn('colors should have the following format. "#xxxxxx"')`

**Comment by ClickerMonkey** [comment]
Yeah, that makes a lot of sense!

**Comment by WolfgangAl** [comment]
But if you are going to add a warning, why not just add in https://www.w3schools.com/lib/w3color.js instead?

**Comment by ClickerMonkey** [comment]
I'm trying to avoid adding more dependencies, but you can override the parseColor method yourself in the plug-in options.
