### ISSUE TITLE
First day of the week

### ISSUE THREAD

**Issue by vandroids** [ClickerMonkey/dayspan-vuetify#102]
Hi!

Can you please tell me how to change first week day from Sunday to Monday? I can't find this option.

**Comment by ClickerMonkey** [comment]
It's not an option in this version of the library. When vuetify releases the calendar component around December it will be integrated into this library and available then.

**Comment by vandroids** [comment]
Ok, thank you.

**Comment by pwnz22** [comment]
Any updates on this?
