### ISSUE TITLE
Custom event create&edit dialog

### ISSUE THREAD

**Issue by pwnz22** [ClickerMonkey/dayspan-vuetify#103]
How can i fully customize event create&edit dialogs?

Is there any custom example? I know it's noob question. Give please some tips.

I want all custom fields in event adding dialog instead of current fields (location, calendar, color, icon etc)

**Comment by ClickerMonkey** [comment]
You can override the `eventPopover`, `eventCreatePopover`, and `calendarAppEventDialog` if using `ds-calendar-app`. Look into the `src/components/CalendarApp.vue`.

Just search through the components and the slots in them to see what you can override.
