### ISSUE TITLE
Customize Components *.vue

### ISSUE THREAD

**Issue by Lunberg88** [ClickerMonkey/dayspan-vuetify#104]
How i could customize component template (for example: src/components/CalendarApp.vue) ?

**Comment by pwnz22** [comment]
You can use slots. For example: 
```
<ds-calendar-app ref="app"
      :calendar="calendar"
      :read-only="readOnly"
      @change="saveState">

      <template slot="title">
        DaySpan
      </template>
</ds-calendar-app>
```
Take a look at this [https://github.com/ClickerMonkey/dayspan-vuetify-example/blob/master/src/App.vue](example)

**Comment by Lunberg88** [comment]
Thanks, but if i want for example remove aside bar (nav drawer- left side) or change v-content class or something else. How i could do it?

**Comment by WolfgangAl** [comment]
Since the drawer is not in a slot you can’t override it. So you are left not using CalendarApp and rolling your own. (The calendar views are in Agenda.vue and Calendar.vue.)

**Comment by Lunberg88** [comment]
If i understand, i can't customize this features?

**Comment by ClickerMonkey** [comment]
Correct. Use plain ds-calendar or just copy the app component and remove what you don't want.

**Comment by WolfgangAl** [comment]
If your requirement is removing the drawer (and not just changing its content): no, you can’t keep CalendarApp.vue and remove the drawer. You can however:
 - change the content of the drawer using the drawerTop (above the date picker), drawerPicker (the date picker) and drawerBottom (below the date picker) slots
 - not use CalendarApp.vue and instead render your own
	- toolbar (CalendarApp provides the title, today, prev, next, summary, view and menuRiight slots here so you’d have to create your own alternatives if you need the functionality within these slots)
        - Agenda.vue component for schedule-type views
        - Calendar.vue component for the other views
        - EventDialog.vue component for event adds/clicks (CalendarApp provides the calendarAppEventDialog slot)
        - Calendar options management (CalendarApp provides the calendarAppOptions slot)
        - Calendar prompter (CalendarApp provides the calendarAppPrompt slot)

**Comment by escullz** [comment]
Any help on how to build it out in a custom way with these example components? 
Just want a calendar, with possible events shown, a month header and back / next buttons but I can't use the complete web page/app out of the box.

Thx.

**Comment by escullz** [comment]
This is all I have for now. I want the Plans.vue page to have an area with this calendar functioning as the example app. its great justneed to break it up..

`<template>
  <div>

    <div class="col-sm-3" id = "col-one" > 
    </div>
    
    <div class="col-sm-8" id = "col-two">
      <Calendar></Calendar>
    </div

    <div class="col-sm-1" id = "col-two" > </div>

  </div>
</template>



<script>
import { Weekday, Month } from 'dayspan';
import Vue from 'vue';
import Agenda from 'dayspan-vuetify/src/components/Agenda.vue';
import Calendar from 'dayspan-vuetify/src/components/Calendar.vue';

import 'vuetify/dist/vuetify.css'
import 'dayspan-vuetify/dist/lib/dayspan-vuetify.min.css'

export default {
  name: 'Plans',
  data: () => ({
    
  }),
  components: {
    Agenda: Agenda,
    Calendar: Calendar,
  },
  mounted()  {
  },
  methods:{
    
  }
}
</script>`

**Comment by escullz** [comment]
I've now got the calendar appearing. Would love some info on how to access calendar, such as advance next month or return current day.

**Comment by escullz** [comment]
I'm not able to access 
$dayspan via Vue.$dayspan or this.$dayspan inside a component
Console is saying 'Cannot read property '$dayspan' of undefined'

**Comment by doubleprincez** [comment]
please im new to vue in laravel but i would like to use this application for a school project. Since im still not grounded in Vuejs, im having problem displaying ds-calendar-app in laravel vue. Can anyone help me with a way to call the calendar component in laravel vue?

**Comment by x7ian** [comment]
I wanted to be able to anable or disable the drawer according to some condition. 
In order to do this, I modified the CalendarApp component. 
First I added a new prop to it the following way:

```
useDrawer:
    {
      type: Boolean,
      default: true
    },
```

then I added a v-if condition to the v-navigation-drawer component like this:

```
<v-navigation-drawer fixed app
    v-if="useDrawer"
    v-model="drawer"
    :clipped="$vuetify.breakpoint.lgAndUp">

```
So now I can do this in my App.vue:

```
<ds-calendar-app ref="app"
      :calendar="calendar"
      :read-only="readOnly"
      :use-drawer="false"
      @change="saveState">

```

instead of false you can use a variable than can be then modified in a method if you want to be able to show or hide the drawer based on a particular condition.
