### ISSUE TITLE
How to save event times to database

### ISSUE THREAD

**Issue by pwnz22** [ClickerMonkey/dayspan-vuetify#105]
How could i save event times to database to use them for loading state from database in future? Is there some helpers in ```schedule object``` to get formatted date?

I can get ```schedule.duration``` and ```schedule.durationUnit```. But what about date timestamp?

**Comment by pwnz22** [comment]
Can someone give tips how to get the time (d.m.y h:i:s) to save to the database?

**Comment by ClickerMonkey** [comment]
An event has a schedule which has a toObject function. Pass true to that function to get a serializable Jon structure.

**Comment by pwnz22** [comment]
![img](https://i.imgur.com/CFgdjGw.png)

I can't see this toObject function. Am i doing that in wrong state? I'm getting schedule after adding.

**Comment by ClickerMonkey** [comment]
ToInput is it!

**Comment by pwnz22** [comment]
Can i do the revert action, turn a dateString (ex: 2018-11-2 12:00:00) to dayspan object to pass to schedule event? 
Im using custom datePicker.

**Comment by ClickerMonkey** [comment]
Schedule has toInput and fromInput to go back and forth between JS object and Dayspan Schedule. If you want a different data type you'll have to do your own parsing. If you do your own you will probably lose the move/cancel/remove/copy functionality because that data is stored in a schedule. Repeatable events also wouldn't work.

**Comment by pwnz22** [comment]
I can't find fromInput :(

**Comment by damqhieu** [comment]
> Tôi không thể tìm thấy fromInput :(

hey bro. you saved event in database ? can you tutorial me ?

**Comment by WolfgangAl** [comment]
Có chí làm quan có gan làm giàu 😉 

With the documentation as it is, we’ll need to do a bit of digging around to find our way here.

In CalendarEventCreatePopover.vue you’ll notice that in the save() method it creates an event, adds it to dayspan and then emits ‘event-create’. (Ignore the ‘creating’ event.)

Now we can add an event handler for ‘event-create’ in the .vue file you use to load in CalendarApp.vue.

‘event-create’ gives you a DaySpan Event as payload. This object has two properties of interest when you want to save this to a database; ‘data’, which contains stuff like title, description, icon et cetera and ‘schedule’, which contains the DaySpan Schedule for the event. 

If you don’t add any complex data members to ‘data’ you can just JSON.stringify this structure. Schedule however is a complex type so just JSON.stringifying is not recommended. Instead, use the Schedule.toInput method to turn it into an easily stringified structure.

You can now create a JSON object containing event data and schedule. Do with this what you want. (Probably something with a POST to a backend that puts it in your database.)

To read events back into dayspan you need to convert them back into DaySpan Event instances. To do this, use Parse (from dayspan, not dayspan-vuetify). This has an event() method which takes your (simple) event structure and turns it into a DaySpan Event and Schedule. Important; this method expects the structure you feed it to have a ‘data’ member for Event.data and a ‘schedule’ member for Event.schedule.

Hope this helps you along.

**Comment by damqhieu** [comment]
thank you so much

**Comment by damqhieu** [comment]
@WolfgangAl Thank you so much
