### ISSUE TITLE
Events displaying on same line

### ISSUE THREAD

**Issue by AudricCh** [ClickerMonkey/dayspan-vuetify#106]
Hi,

Thanks for your calendar, it's very powerfull and complete, but I've got a pretty annoying problem.

When I've created a new event on a day which already have an event, the new one go one the same line than the other, so we can't see the two events on this day.

I was thinking it was my dev, but I've tryed on your example and I arrived to reproduce the same bug just when we create two events a day.

I join to this a picture because I'm not sure to be really clear.

![sans titre](https://user-images.githubusercontent.com/25503027/47926210-54a53380-dec0-11e8-9ac4-9ea006d8d25e.png)

Thank you !

Regards,
Audric

**Comment by ClickerMonkey** [comment]
I can't reproduce the bug, can you document which browser and steps I need to take to reproduce it?

**Comment by AudricCh** [comment]
I've tryed with :
- Google Chrome last build (70.0.3538.77) 64 bits
- Mozilla Firefox (Quantum) 63.0 64 bits
- Internet Explorer 11 (11.1358.14393) (blank page on https://clickermonkey.github.io/dayspan-vuetify/example/)

I went to your example : https://clickermonkey.github.io/dayspan-vuetify/example/
I've created a one day event (a blue one on the 11th november for example)
Then I've created another one in two days (can be a one day event with the same day) in purple between the 11th and 12th november

Now I just can see the last added (the purple one)
If I move it, then I can see behind the first event in blue

There is two captures.
The first is when I've created the two events (so the blue is behind the purple)

![ex1](https://user-images.githubusercontent.com/25503027/48051833-7fd0a100-e1a6-11e8-8de0-61a0e90b5e23.png)

When I'm dragging the purple, I can see the blue (the dragging one is well put under the blue) but if I stop dragging, it go on the first line and back to the first screenshot

![ex2](https://user-images.githubusercontent.com/25503027/48051942-d76f0c80-e1a6-11e8-9047-af0809e4f52a.png)

Hope it's clear, but I don't understand how I've got this problem and nobody notice it

Thanks !

**Comment by AudricCh** [comment]
Well, I've found what I was needed, I had to do the calendar rebuild method to update the calendar.
Like this : 
this.$refs.calendar.rebuild(undefined, true, this.$refs.calendar.calendar.currentType)

It change the event display and it's well place after doing this.
I don't know if it's the correct method to resolve the problem but it's working.

**Comment by mtx-z** [comment]
Same issue here, @AudricCh solution worked, but I had to make few changes : 

`this.$refs.app.rebuild(undefined, true, this.$refs.app.currentType);`

**Comment by WolfgangAl** [comment]
It seems the v-menu divs that are rendered for the CalendarEvents are already stacked. component:getStyleFull undoes this by rendering each event with a `top` offset equal to the (negative) index * eventHeight, effectively rendering them all on top of each other.

Thus, changing top to '0' in getStyleFull also solves this issue

**Comment by ClickerMonkey** [comment]
If there are overlapping events, inspect your Calendar object and ensure `updateRows` is set to `true` - that calculates the row to which the events should be rendered on.

Let me know if that helps.

**Comment by WolfgangAl** [comment]
@ClickerMonkey that helped me along quite a bit. The problem is in the way I (and I guess the others as well) create the DaySpan Calendar to load into CalendarApp. I just copied your example of
```
{
  data: vm => ({
    calendar: Calendar.months()
  })
}
```
But this creates a Calendar with the default setting for updateRows, which is `false`. The solution is to change that line to
```
{
  data: vm => ({
    calendar: Calendar.months(undefined,undefined,undefined,{
      fill: true,
      updateRows: true
    })
  })
}
```
And now it renders correctly

**Comment by ClickerMonkey** [comment]
Thanks for the heads up. I will look into adding updateRows: true as the default for calendar: months - and make sure it won't have any adverse effects.
