### ISSUE TITLE
Some translations are missing

### ISSUE THREAD

**Issue by AudricCh** [ClickerMonkey/dayspan-vuetify#107]
Hello,

I'm sorry to open another issue but it's not the same problem than the other ticket I've opened.
I'm actually using the french translation, which is working well.

But I saw that a small part of translation are missing.
I've attached some pictures to show these ones.

![sans titre](https://user-images.githubusercontent.com/25503027/47927380-70f69f80-dec3-11e8-82bd-d2f5238a842b.png)
![sans titre2](https://user-images.githubusercontent.com/25503027/47927381-718f3600-dec3-11e8-9b53-1e0863e81f84.png)
![sans titre3](https://user-images.githubusercontent.com/25503027/47927382-718f3600-dec3-11e8-9bf7-835610796d28.png)

If needed, I can translate myself and do a pull request, but their are not even in the english translation file, so I can't do it.

Thank you for all

Best regards,
Audric

**Comment by ClickerMonkey** [comment]
Some of it is the Dayspan library which does not have locale support for
schedule occurrence descriptions and 7th - and the other is the momentjs
dependency which does not support "live" locale changes.

There are plans in the future to get off of momentjs and add localization
to Dayspan but it might not happen for a month or two.
