### ISSUE TITLE
[Vuetify] 'id' is deprecated, use 'value' instead

### ISSUE THREAD

**Issue by yamin27** [ClickerMonkey/dayspan-vuetify#111]
I got this warning 
![image](https://user-images.githubusercontent.com/10800658/48392051-b755c500-e733-11e8-9c5a-47daa6bbe2a8.png)

![image](https://user-images.githubusercontent.com/10800658/48392029-9e4d1400-e733-11e8-9ebc-ce472345fecb.png)

**Comment by ClickerMonkey** [comment]
Looks like a newer version of vuetify changed this. I'll update it.
