### ISSUE TITLE
ds-calendar-app in a div container

### ISSUE THREAD

**Issue by deep0410** [ClickerMonkey/dayspan-vuetify#113]
This template is wrapped in another component. 

**So I need the calendar APP to be restricted to display within the div, but for some reason, it keeps injecting the files into the main '#app'**

```
<template>
    <div id="calendarContainer">
        <v-container id="dayspan" v-cloak>
            <ds-calendar-app :calendar="calendar"></ds-calendar-app>
        </v-container>
    </div>
</template>

<script>
    import { Calendar } from 'dayspan';

    export default {
        name: 'calendarContainer',
        data: () => ({
            calendar: Calendar.months()
        }),
        mounted(){

        }
    }
</script>

<style>
    #calendarContainer, #dayspan {
        font-family: Roboto, sans-serif;
        width: 100%;
        height: 100%;
    }
</style>

```
Also, I am getting that in console.
```
[Vuetify] Unable to locate target [data-app]
```

**Comment by diegotejadav** [comment]
Same need here!
I'm using NuxtJS to have a basic template, but it's getting replaced but the whole calendar.

**Comment by deep0410** [comment]
For anybody, that might need help with this. 
my current fix was these styles: 
```
#dayspan {
            font-family: Roboto, sans-serif;
            width: 100%;
            height: 100%;
        }

        .v-toolbar--clipped{
            position: relative;
        }

        .v-dialog__content{
            position:absolute !important;
        }
        .v-navigation-drawer--fixed{
            z-index:5;
            position:absolute;
        }
        .v-toolbar__content, .v-toolbar__extension{
            top: 0;
            position: sticky;
            width:100%;
            left: 0;
        }

        .v-content{
            position:absolute;
            top: 0;
            left: 0;
        }

        .v-content__wrap{
            z-index: 3;
        }
        .v-menu__content{
            position:fixed;
        }
        .v-dialog__content{
            position:fixed !important;
        }
        .v-dialog{
            width:auto;
            border-radius: 15px;
            box-shadow: 3px -1px 43px 12px rgba(0,0,0,.5);
        }
        .application--wrap{
            height:100%;
            min-height:unset;
        }
```

**Comment by ibbtek** [comment]
I had also problems while trying to insert this calendar into an existing application as a component.

The workaround I found was to extends the [CalendarApp.vue](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarApp.vue), get rid of the the toolbar and sidebar in the template. Then I also removed the **<v-content class="ds-expand">** tag and use my new locale **CalendarApp.vue** file instead of the original one and everything is working like a charm.

Check the **CalendarApp.vue** file on [this fork](https://github.com/ibbtek/dayspan-vuetify/blob/master/src/components/CalendarApp.vue) for an example.

By the way, this dayspan-vuetify is awesome! Great Job!

**Comment by damqhieu** [comment]
i want use `ds-calendar-app ` in application  as a component. i try like @ibbtek  but it not working for me. 
```<template>
  <v-app id="dayspan" v-cloak>
    <ds-calendar-app :calendar="calendar"></ds-calendar-app>
  </v-app>
</template>


<script>
import { Calendar } from 'dayspan'
import 'vuetify/dist/vuetify.min.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'dayspan-vuetify/dist/lib/dayspan-vuetify.min.css'

export default {
  name: 'Plan',
  data: () => ({
    calendar: Calendar.months()
  }),
  methods: {

  }
}
</script>
```
`CalendarApp.vue` i fixed  [https://github.com/ibbtek/dayspan-vuetify/blob/master/src/components/CalendarApp.vue](url) . it  keeps injecting the files into the main '#app' . Pls help me

**Comment by damqhieu** [comment]
It does not seem to have any effect when I edit, even deleting the component directory at the node-modules / dayspan-vuetify / component.

**Comment by damqhieu** [comment]
my solution is change file package.json in dayspan-vuetify , edit `"main": "src/lib.js",` . its working great

**Comment by klaveren** [comment]
@ibbtek Wow man. you're job is amazing. This works perfect. thank you.
