### ISSUE TITLE
EventCreatePopover not working

### ISSUE THREAD

**Issue by jessielaf** [ClickerMonkey/dayspan-vuetify#126]
Hi!

I have used your library and I love it. I only have one question. When I try to fill the eventCreatePopover it opens the eventPopover and skips the eventCreatePopover template. It also just disappears.

![Gif of how it looks](https://user-images.githubusercontent.com/23742276/49079116-180af480-f240-11e8-9623-52d7a05dd766.gif)

![How the code looks](https://user-images.githubusercontent.com/23742276/49078996-ce220e80-f23f-11e8-9fe8-9806ac71430f.png)

Can you help me?

I have been able to make a workaround by checking if the meta is set of the schedule object

**Comment by ClickerMonkey** [comment]
Try putting a v-card in your code instead of `tst` and let me know if it solves the problem.

**Comment by jessielaf** [comment]
Hi,

Sorry for my late response. I changed it to v-card but i have to press 4 or 6 times and the card disappears automatically.

![The code](https://user-images.githubusercontent.com/23742276/49373364-28b6e100-f6fe-11e8-8a74-aa9b12868233.png)

![How it looks](https://user-images.githubusercontent.com/23742276/49373360-205ea600-f6fe-11e8-9bb2-dd34629d538a.gif)

**Comment by ClickerMonkey** [comment]
I haven't witnessed this, so if you want me to figure this out I need this issue recreated in something I can access to I can investigate it!

**Comment by ClickerMonkey** [comment]
I'm closing this issue since I haven't gotten anything that allows me to recreate the issue. If you can recreate the issue outside your environment (in something like Codepen) please open this issue back up.
