### ISSUE TITLE
How can I set the schedule?

### ISSUE THREAD

**Issue by deep0410** [ClickerMonkey/dayspan-vuetify#127]
I currently have a schedule. How can I update the start date?
also, is it possible to set up drag and extend on the event in the calendar

**Comment by deep0410** [comment]
```
        let start_date = moment().subtract(1, 'days');
        let schedule = new Schedule(start_date);
````
Tried that, getting an error. 
![0](https://user-images.githubusercontent.com/33726731/49379342-e630dc80-f6dc-11e8-893e-0343dea2ab21.PNG)

**Comment by WolfgangAl** [comment]
Try new Schedule{{start: start_date}).

**Comment by deep0410** [comment]
Thanks @WolfgangAl

**Comment by deep0410** [comment]
```
this.schedule.set({
            year:[start_date.year()] , month:[start_date.month()] , dayOfMonth:[start_date.date()],
            times:[{hour: start_date.hours() , minute: start_date.minutes()}]
        });
```

**Comment by ClickerMonkey** [comment]
If you would've checked out the documentation you would see exactly what you want!

https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#forday
