### ISSUE TITLE
How can i change currentType programatically?

### ISSUE THREAD

**Issue by pwnz22** [ClickerMonkey/dayspan-vuetify#129]
I want save picked currentType to localStorage and on mounted set picked state.

Can you please give a tip how can i change currentType?

![currentType](https://i.imgur.com/rrRPEhx.png)

**Comment by ClickerMonkey** [comment]
It's decided by the type and size of the Calendar you passed to the component. So change that calendar with https://clickermonkey.github.io/dayspan/docs/classes/calendar.html#set .

**Comment by pwnz22** [comment]
Can you please provide a little example? What i can pass to this method?

**Comment by WolfgangAl** [comment]
Just take a look at CalendarApp and how it handles currentType changes:
```
currentType:
    {
      get()
      {
        return this.types.find((type) =>
          type.type === this.calendar.type &&
          type.size === this.calendar.size
        ) || this.types[0];
      },
      set(type)
      {
        this.rebuild(undefined, true, type);
      }
    }
```
<pre><code>
    rebuild (aroundDay, force, forceType)
    {
      let type = forceType || this.currentType || this.types[ 2 ];

      if (this.isType( type, aroundDay ) && !force)
      {
        return;
      }

      <b>let input = {
        type: type.type,
        size: type.size,
        around: aroundDay,
        eventsOutside: true,
        preferToday: false,
        listTimes: type.listTimes,
        updateRows: type.updateRows,
        updateColumns: type.listTimes,
        fill: !type.listTimes,
        otherwiseFocus: type.focus,
        repeatCovers: type.repeat
      };</b>

      this.setState( input );
    },
</code></pre>
<pre><code>
    setState(state)
    {
      state.eventSorter = state.listTimes
        ? Sorts.List([Sorts.FullDay, Sorts.Start])
        : Sorts.Start;

      <b>this.calendar.set( state );</b>

      this.triggerChange();
    },
</code></pre>

**Comment by pwnz22** [comment]
Okay. Now im doing something like ```this.calendar.set(this.$dayspan.defaults.dsCalendarApp.types[0]))``` but it working strange. Sometimes not working.

**Comment by WolfgangAl** [comment]
Well, 'working strange' and 'sometimes not working' are a bit hard to judge from here :) Maybe your code in `mounted()` doesn't trigger a reactive property (like `currentType`, which defaults to `types[0]` anyway (even though Calendar defaults to `types[2]`)) to change?

**Comment by pwnz22** [comment]
Except 1 day and 4 days others are working. When i'm calling this ```this.calendar.set(this.$dayspan.defaults.dsCalendarApp.types[5])``` in mounted.

**Comment by ClickerMonkey** [comment]
Try calling `this.$refs.app.rebuild( undefined, true, type )` where type is the one you want to set. It's the code seen in the `set currentType (type)`.
