### ISSUE TITLE
dsCalendarApp Types

### ISSUE THREAD

**Issue by MarioBrendel** [ClickerMonkey/dayspan-vuetify#133]
First of all - Great application that you've written.

I've wanted to have a schedule view and calendar view for each type (day, week, month), so I've configured the default.js but if I choose to have the same type and size I can't display 1 of the views.

i.e.
`
{id: 'D', label: LOCALE_ENTRY, shortcut: 'D', type: Units.DAY,   size: 1,  focus: 0.4999, repeat: true,  listTimes: true,  updateRows: true,  schedule: false },

{id: 'DL', label: LOCALE_ENTRY, shortcut: 'DL', type: Units.DAY,   size: 1, focus: 0.0000, repeat: true, listTimes: true, updateRows: false, schedule: true },
`

The day list will not be shown since the code within the calendar.js says:
`
        var typeChange = fn.isDefined(input.type) && input.type !== this.type;

        var sizeChange = fn.isDefined(input.size) && input.size !== this.size;

        if (typeChange || sizeChange) {...
`

Is there any workaround for this? Maybe it would be good if the set function would check for the id?
Thanks in advance

**Comment by WolfgangAl** [comment]
Is this the real problem? Because I don't think you need a Calendar change; it doesn't need to rebuild events if it's already displaying the correct set of events. Whether or not this is in a Schedule view is not handled by DaySpan Calendar but by dayspan-vuetify CalendarApp.
```
<div v-if="currentType.schedule" class="ds-expand">

          <slot name="calendarAppAgenda" v-bind="{$scopedSlots, $listeners, calendar, add, edit, viewDay}">

            <ds-agenda
              v-bind="{$scopedSlots}"
              v-on="$listeners"
              :read-only="readOnly"
              :calendar="calendar"
              @add="add"
              @edit="edit"
              @view-day="viewDay"
            ></ds-agenda>

          </slot>

        </div>
```
The problem is the getter for currentType:
```
    currentType:
    {
      get()
      {
        return this.types.find((type) =>
          type.type === this.calendar.type &&
          type.size === this.calendar.size
        ) || this.types[0];
      },
      set(type)
      {
        this.rebuild(undefined, true, type);
      }
    },
```
This will always return your Day calendar view instead of your Day schedule view...

I think your best bet is extending CalendarApp and overriding `currentType`...

**Comment by MarioBrendel** [comment]
Yea you are right - this is my actual problem :). I think you are right, there is no other way than extending this. Thanks a lot for your help
