### ISSUE TITLE
Change color to ds-calendar-event based on a condition

### ISSUE THREAD

**Issue by mmckalan** [ClickerMonkey/dayspan-vuetify#134]
Hello,

I am working on a project made in Vue.js, AirBnB style where you have just one calendar, with appointments that you've created to visit your property and appointments that a potential buyer has proposed to you.
What I need now is to change the color of the ds-calendar-event based on my isOwner property.

I can change colors by adding a new class to ds-calendar-event in the stylus on my calendar page but I can't use conditional classes based on Vue.js there.

I couldn't either find a ds-calendar-event to bind conditional classes by Vue.

Is there an easy way to achieve this? Where could I find that specific element?

Thanks in advance.
Best,

**Comment by ClickerMonkey** [comment]
An event has a data and a schedule property. The data object has the title, description, and can also be given a color value in the format #nnnnnn .
