### ISSUE TITLE
Can edit event even when it is Read Only

### ISSUE THREAD

**Issue by zestiros** [ClickerMonkey/dayspan-vuetify#136]
When a schedule is read only , you cannot add more events , But you can modify an already existing event ! I just wanted to make you aware of it !! Btw this scheduler is amazing , thanks for your hard work!!

**Comment by ClickerMonkey** [comment]
How are you making the schedule read-only?

**Comment by ClickerMonkey** [comment]
Provide some example code please! Screenshots help as well

**Comment by zestiros** [comment]
I'm sorry it's my bad i made a mistake
