### ISSUE TITLE
Mark a day in left DayPicker with colored dot if there are any events

### ISSUE THREAD

**Issue by pwnz22** [ClickerMonkey/dayspan-vuetify#137]
If there is way to make left DayPicker to mark with colored dot if there are events on that day?
https://vuetifyjs.com/en/components/date-pickers#example-date-events

**Comment by ClickerMonkey** [comment]
I like the idea, but I don't have to implement the feature. Feel free to do it yourself!

You can specify the `drawerPicker` slot in the `ds-calendar-app` component alternatively. slot scope has the `calendar` and `picked` variables available.
