### ISSUE TITLE
More generic support, usage without vuetify

### ISSUE THREAD

**Issue by eezhal92** [ClickerMonkey/dayspan-vuetify#138]
Hello, thanks for making awesome library.

I'm wondering if it is possible to use this calendar library without vuetify? I tried using it with vuetify, but it ended breaking my app styling.

Looking forward for the response, thanks.

**Comment by naulacambra** [comment]
Check [Dayspan](https://github.com/ClickerMonkey/dayspan) ;)

**Comment by ClickerMonkey** [comment]
Dayspan is the supporting library which does the heavy lifting - this library is the interface which uses Vuetify. If you want another interface you'll have to do it yourself for now.
