### ISSUE TITLE
Edit Components

### ISSUE THREAD

**Issue by pcm0nk** [ClickerMonkey/dayspan-vuetify#140]
Hi,
im trying to edit any component example(node_modules/dayspan-vuetify/src/components/Event.vue) but nothing is taking effect!?????
also in the header  trying to move the popover box to the right a bit , cant find any place to do it.
![capture](https://user-images.githubusercontent.com/43221471/50374597-b30baa00-0605-11e9-9fd6-8e48be621429.JPG)

need help.
thanks in advanced

**Comment by pwnz22** [comment]
Use slots for that. It's not recommended to edit node_modules files. 
https://github.com/ClickerMonkey/dayspan-vuetify/issues/104#issuecomment-435023972

**Comment by pcm0nk** [comment]
Hi @pwnz22 ,tnx for your reply.
Can you please elaborate ? 
ill explain a bit about my situation that might help
since im using laravel inside in resource/assets/js/components I have made a new component and copeid app.vue from the node_modules/dayspan/vuetify/src/ and paste it there,I had to remove this line 
`import { dsMerge } from './functions';
to get basic funtionality but still having problem adjusting the HTML and loading some parts.
Also about the slot , Im having problem finding the right menu which is open in the picture.
and how to get the event detail and other tabs working on eiditing events ?
Thanks again.

**Comment by pwnz22** [comment]
Look at this example: https://github.com/ClickerMonkey/dayspan-vuetify-example
