### ISSUE TITLE
How to modify the way schedule/ event is entered (bypassing the dialog)

### ISSUE THREAD

**Issue by tuing2ing** [ClickerMonkey/dayspan-vuetify#142]
Hi,
Can anybody suggest how to modify dayspan-vuetify so that: When and I click a cell in Week View (for example on 30th Dec between 12am and 1am), I can bypass the dialog and directly enter the event title with a given value (for example, the event title will be the username of my app).

Thanks in advance.

**Comment by ClickerMonkey** [comment]
There's an event `adding` which passes an event object which has a `handled` property. Set `ev.handled = true` to keep the popup from occurring.
