### ISSUE TITLE
Using v-html makes the app susceptible to XSS.

### ISSUE THREAD

**Issue by griest024** [ClickerMonkey/dayspan-vuetify#143]
See [this](https://vuejs.org/v2/guide/syntax.html#Raw-HTML).

```
Dynamically rendering arbitrary HTML on your website can be very dangerous because it can easily lead to XSS vulnerabilities. Only use HTML interpolation on trusted content and never on user-provided content.
```

Event details are not necessarily sanitized and I think that `v-html` calls should be removed.

**Comment by ClickerMonkey** [comment]
This is a feature still desired, so I added a notice to the README:

https://github.com/ClickerMonkey/dayspan-vuetify/commit/c484c360468cd0ccad1e58d04c93a3c8f65dd8a7#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by ClickerMonkey** [comment]
How would you propose making it configurable?

**Comment by griest024** [comment]
Either with a prop on the component, or having `renderedDetails` field on the eventData. If either of these things are present, then we can use `v-html`. Most of these are in slots anyway, so its not like we have to make a perfect solution, but I don't think we should be using `v-html` by default.

**Comment by griest024** [comment]
Or if you *do* want to keep `v-html` on by default, we could sanitize everything before injecting it.

**Comment by griest024** [comment]
With that said, you do have a notice about data sanitation now, so I guess its fine either way.
