### ISSUE TITLE
dsCalendarApp Types isnt a dropdown menu

### ISSUE THREAD

**Issue by marko-mlinarevic** [ClickerMonkey/dayspan-vuetify#152]
I'm having a problem with Calendar app component. dsCalendarApp shows only day there is no dropdown when I click on a button. What could be a problem?

**Comment by marko-mlinarevic** [comment]
my bad it was css problem

**Comment by ClickerMonkey** [comment]
What version of Vuetify

**Comment by ClickerMonkey** [comment]
Okay!

**Comment by marko-mlinarevic** [comment]
great calendar by the way thanks a lot
