### ISSUE TITLE
Locale not applied

### ISSUE THREAD

**Issue by xplodwild** [ClickerMonkey/dayspan-vuetify#153]
Hello

Simple repro case: https://clickermonkey.github.io/dayspan-vuetify/example/ - select French language, the "app" interface will turn in French, however the actual calendar will keep on using the English day names. 

Also, is there a way to set Monday as the beginning of the week, instead of sundays?

Thanks

**Comment by ClickerMonkey** [comment]
This is due to a limitation in moments, but I hope to remove that dependency in the next major release. There's another issue to handle it.
