### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Brandon300055** [ClickerMonkey/dayspan-vuetify#154]
<img width="1005" alt="screen shot 2019-01-25 at 1 16 52 pm" src="https://user-images.githubusercontent.com/24799695/51770737-f5605500-20a3-11e9-85d0-95b0a534918b.png">

**Comment by naulacambra** [comment]
Which is your code that is provoking this error?

**Comment by Brandon300055** [comment]
if i use this it breaks 
// Vue = require('vue');
how ever removing fixes it
