### ISSUE TITLE
All events in the Month view showing up as all-day event banners

### ISSUE THREAD

**Issue by MiguelNepomuceno** [ClickerMonkey/dayspan-vuetify#157]
Created new Vue project with app.js, App.vue and index.html all according to Example code. Issue is happening on both Chrome and Firefox browsers. 

-	Created “Event 1” as an all-day event on Jan 29, 2019.
 
![event_bug1](https://user-images.githubusercontent.com/31608734/51886142-9cb1f480-23e2-11e9-812f-6b99156ea9c1.png)

-	Created “Event Test 2” as an event on Jan 28, 2019 at 7.00 AM.

![event_bug2](https://user-images.githubusercontent.com/31608734/51886147-a9364d00-23e2-11e9-874b-a883467c2455.png)

All-day events in the Day view are showing as an event banner (covering week day label TUE)

![event_bug3](https://user-images.githubusercontent.com/31608734/51886161-b8b59600-23e2-11e9-90af-32b4ecbab3d1.png)

Events in the Week view.
-	All-day event “Event Test 1” showing as banner for the whole week (covering week day labels SUN to SAT)
 
![event_bug4](https://user-images.githubusercontent.com/31608734/51886186-d125b080-23e2-11e9-99aa-917d56fe25d9.png)

Events in the Month view are showing as all-day event banners. 
-	Time specific event “Event Test 2” not showing up on the Month calendar view.
 
![event_bug5](https://user-images.githubusercontent.com/31608734/51886199-d84cbe80-23e2-11e9-90fc-212a58cf4c6b.png)

-	When deleting event “Event Test 1” in the Month view, “Event Test 2” banner will show.
 
![event_bug6](https://user-images.githubusercontent.com/31608734/51886202-dc78dc00-23e2-11e9-97cd-b419ae4718f4.png)

**Comment by ClickerMonkey** [comment]
If you could provide a codepen with the issue that would allow me to address the problem. I don't have this occurring anywhere, so it looks like styles are being overridden.

**Comment by minesguy82** [comment]
I've had this same issue too. After some comparing styles between the example and what I was running, I noticed that the style for the event that is inherited from div.v-menu__activator in the example includes a 'position: relative;' tag, and the one that I'm using doesn't include that line. Including the following in my component that implements Dayspan stuff fixed it in my app:

`.v-menu__activator {
     position: relative;
}`

**Comment by MiguelNepomuceno** [comment]
@minesguy82 That has resolved the issue. Thanks.

@ClickerMonkey I referred to the following code https://github.com/ClickerMonkey/dayspan-vuetify-example/blob/master/src/App.vue

**Comment by AudricCh** [comment]
Hello,

I've got the same problem, and your answer does not help me.
In the Chrome debugger, I can see that the "v-menu__activator" is well placed :
![1](https://user-images.githubusercontent.com/25503027/54117324-c4887500-43f0-11e9-80f1-141526393635.png)

But the "ds-calensar-event" is the one which stick to the top with some weird CSS
`top: 0px;
left: 0px;
right: 0px;`

![2](https://user-images.githubusercontent.com/25503027/54117450-1630ff80-43f1-11e9-9ae9-1f573f7cc6bd.png)

Maybe it's a problem about the chunk-vendors.79ef74f7.css which is telling me that it have a local version different but I don't get it at all...

![3](https://user-images.githubusercontent.com/25503027/54118166-b63b5880-43f2-11e9-956b-94fb378fa731.png)

And a fun fact : events are well placed in my localhost version but when it been deployed, the problem appear. I'm using same browser and same build of my application.

If you have some ideas, thanks to let me know !

**Comment by ClickerMonkey** [comment]
Yeah, newer versions of Vuetify change styling quite frequently, Until v-calendar is used from vuetify, this library won't be stable with newer versions.
