### ISSUE TITLE
Weird 'all day' event in a Nuxt project (with demo)

### ISSUE THREAD

**Issue by chulman444** [ClickerMonkey/dayspan-vuetify#160]
I did not expect nuxt to not server Dayspan-vuetify properly. I need your help.

Here is the minimal setting that I'm testing with:
* https://github.com/chulman444/dayspan-vuetify-nuxt-bug-demo

The all-day events, no matter the duration, takes the whole width of the `v-content`, located at the top of `v-content` (right below the `v-toolbar`), located on top of each other. When the `v-navigation-drawer` is hidden, it takes the whole width of the application. Dragging doesn't work properly either.

However, events less than 24 hours doesn't seem to have any problems. Again, Vue-served dayspan-vuetify has no problem for me.

I even compared the css of the nuxt-served and vue-served dayspan-vuetify but there doesn't seem no difference.

Please help!

**Comment by ClickerMonkey** [comment]
I don't know anything about nuxt so I'm afraid I can't be of any help here. My only goals for this library are for Vue & Vuetify support. I don't have time for much else!

If you find a solution please share and I will see if I can make it in this library without interrupting the expected uses.
