### ISSUE TITLE
Hide the mini calendar by default?

### ISSUE THREAD

**Issue by Rhonage** [ClickerMonkey/dayspan-vuetify#162]
Hey, this is a great calendar - thanks very much for creating it @ClickerMonkey 

I am however having an issue with 'admin style' templates (with a sidebar). TranslateX CSS pushes it before it. I'm just wondering if there's a way to have it layout correctly with my template, or hide it by default (I just want to see the calendar itself).

Screenshots here: https://imgur.com/a/tahvgu8

Thanks in advance!

**Comment by ClickerMonkey** [comment]
Thanks!

Do some searching in the docs and you should be able to remove it by
overriding a slot.

Or just use the ds-calendar component and not the ds-calendar-app. If
there's still some functionality that you like, copy the ds-calendar-app
component and remove what you don't want.

If you don't need Dayspan, I've made a calendar for Vuetify which was
released in 1.5 and the event calendar will be released in 2.0

**Comment by Rhonage** [comment]
Cheers for your fast response @ClickerMonkey.

Thanks, I'm new to Vue (only started this week), so I'll look into slots and your suggestion re: ds-calendar.

Actually all I'm looking for is a nice looking Calendar that can add and display events. Do you have a different package you would recommend? (similar to Google Calendar)

Thanks again!

**Comment by pwnz22** [comment]
https://vuetifyjs.com/en/components/calendars

**Comment by ClickerMonkey** [comment]
^^^ That's the vuetify calendar I've worked on, and in 2.0 will be greatly improved.
