### ISSUE TITLE
Schedule "End" property should be "inclusive" but seems not to be in dayspan-vuetify

### ISSUE THREAD

**Issue by mtx-z** [ClickerMonkey/dayspan-vuetify#164]
Hello,

I'm running into an issue using [Schedule End property](https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#end).
As dayspan documentation says: 

> This day is inclusive.

But from my test: 

- I create the following Schedule: 
```
{
	data: {
		title: 'TestSchedule',
		color: '#b55176'
	},
	schedule: {
		dayOfWeek: [3],     //Wednesday 
		end: [2019, 2, 20],
		times: [3012],
		duration: 120,
		durationUnit: 'minutes',
		start: [2019, 2, 13],
	}
}
```
- It's from `13/03/2019` to `20/03/2019` (Wednesday 13/03 to Wednesday 20/03)

`13/03/2019` event is correctly displayed on the Calendar. But Wednesday `20/03/2019` is not. To me, it should as its the End property of Schedule, which is inclusive right? If I set the End to `21/03/2019` instead of `20/03/2019`, the `20/03/2019` event is now displayed on Calendar.

Am I missing something? 
Thanks

EDIT: should I use [Schedule.include](https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#include) to manually add the end day?

**Comment by ClickerMonkey** [comment]
when we say "2019-02-20" it assumes the default hours and minutes of the day which are 0. So when it's specified as the end date it's exclusive. Your option for now is to pass `[2019, 2, 20, 23, 59, 59, 999]` or just pass the next day `[2019, 2, 21]`.

I'll think about the option to specify endInclusive or something, but don't hold your breath on having it implemented anytime soon!

**Comment by mtx-z** [comment]
It works! Thanks :) 

I'll go with the `23, 59, 59, 999` solution to prevent the next day at exactly 00:00:00:000 to be included. I didn't think of this as their's also the [time](https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#times) and the [duration](https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#duration) properties. But it makes sense now. Thanks again!
