### ISSUE TITLE
Styling and positioning re-work

### ISSUE THREAD

**Issue by g1robo** [ClickerMonkey/dayspan-vuetify#170]
Hello, 

I would like to change the v-toolbar and the v-navigation-drawer to a position that is relative so the calendar will not override my working app. I have attempted to change the position for both to relative in the CalendarApp.vue file but they still load in a fixed position overlapping my current app.
Do you know which files will allow me to change the positioning to relative?
Do you what file I can change the theme to dark as well?

**Comment by ClickerMonkey** [comment]
Dark theme is not supported on the current version, and if you want finer control I would move away from `ds-calendar-app` and use `ds-calendar`

**Comment by g1robo** [comment]
How do I access just the ds-calendar?
