### ISSUE TITLE
Customizing the list of icons in the event modal

### ISSUE THREAD

**Issue by connecteev** [ClickerMonkey/dayspan-vuetify#178]
This is more of a question: How do I customize the list of icons in the event modal when I try to create a new event?
Screenshot: https://prnt.sc/n8u7bi

Is there a way to do that without directly modifying node_modules/dayspan-vuetify/src/icons.js
?

I couldn't find an option here https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/component.js

**Comment by ClickerMonkey** [comment]
Everything you see in that file can be overridden when you initialize DayspanVuetify:

https://github.com/ClickerMonkey/dayspan-vuetify#usage

icons is just another object you can pass to data.

**Comment by connecteev** [comment]
Oh, that worked! Very cool :)
