### ISSUE TITLE
Customizing the dropdown on the right (for calendar view)

### ISSUE THREAD

**Issue by connecteev** [ClickerMonkey/dayspan-vuetify#179]
2 more questions.
1. How do you customize the options in the dropdown on the right here? https://prnt.sc/n8wv6b
How do you override the dsCalendarApp.types object from node_modules/dayspan_vuetify/src/defaults.js  in src/main.js?

2. How would you replace the dropdown with icons like this? https://stormseed.github.io/quasar-calendar-demo/
What file(s) would you change?

**Comment by ClickerMonkey** [comment]
This is the code to the app component.

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarApp.vue

If you want something that drastically different just copy it and make it how you want it.
