### ISSUE TITLE
fine tuning calendar

### ISSUE THREAD

**Issue by g1robo** [ClickerMonkey/dayspan-vuetify#180]
How do you access just the ds calendar to fine tune styling?

**Comment by ClickerMonkey** [comment]
I'm not sure I understand the question.

If you are familiar with Vue and Single File Components you can figure out how to do anything you want by just reading the source!

**Comment by ClickerMonkey** [comment]
If you have an issue, please file one with as much detail as possible. I need to keep the "help" out of the GH issues, sorry!

If you are working with dayspan-vuetify for a company and need support, please let me know.

I'm closing this for now.

Thanks,

Phil
