### ISSUE TITLE
Mouse down event

### ISSUE THREAD

**Issue by SopsoN** [ClickerMonkey/dayspan-vuetify#183]
Hey,
I'm using ds-calendar-app and I'm trying to use event @mouse-down, but it doesn't seem to work. Any advice what I'm doing wrong?

`
<ds-calendar-app ref="app"
                             :calendar="calendar"
                             :read-only="readOnly"
                             :drawer="drawer"
                             @mouse-down="getEventsFromDb"
                             >
`

and method:

     getEventsFromDb: function(e, init = false) {

                let THAT = this;

                console.log(e);

                if(init === true) {
                    axios.get(this.calendarfetch).then(function (response) {
                        if (response.data.status === 200) {
                            THAT.defaultEvents = response.data.data;
                            THAT.loadState();
                        }
                        else {
                            THAT.defaultEvents = [];
                            THAT.loadState();
                        }
                    });
                }
            },

**Comment by ClickerMonkey** [comment]
The `@mouse-down` event only works for when you're viewing a week and you click on an empty slot of time.

`@mouse-down-day` is emitted when a day is clicked on the month view OR when the header of the week view is clicked.
`@mouse-down-event` is emitted when an event is clicked.

I hope that clears things up.
