### ISSUE TITLE
Questions on customizing dayspan-vuetify and hot reload

### ISSUE THREAD

**Issue by connecteev** [ClickerMonkey/dayspan-vuetify#184]
I have successfully installed https://github.com/ClickerMonkey/dayspan-vuetify-example

The package.json file contains:
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },

So I ran: npm run serve
and then went to http://localhost:8080/ 
where the calendar was visible for dayspan-vuetify-example
All good so far.

Question 1:
But, I want to make changes to the underlying calendar functionality, namely:

1. I want to make these changes to "Schedule" / Agenda page
See https://prnt.sc/nj5dow
2. I want to make these changes to the event modal:
https://prnt.sc/nj5fe5

Among others.

This is the default folder structure for dayspan-vuetify-example project:
https://prnt.sc/nj5g0f

I made changes to dayspan-vuetify-example/node_modules/dayspan-vuetify/src/components/Agenda.vue (and other files within dayspan-vuetify-example/node_modules/dayspan-vuetify/src/components/)
https://prnt.sc/nj5gvv

Then I ran 'npm run serve' again
https://prnt.sc/nj5i6n

and then went to http://localhost:8080/ 
where the calendar was visible, but the changes I made are NOT being reflected.

Why? How do I make changes to the dayspan-vuetify source code in this project and have it reflect on the front-end?
This is the main question I am struggling with.

Question 2:
On a separate note how do I enable hot reloading? I added a 'hot' option to package.json file:
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "hot": "vue-cli-service hot",
    "lint": "vue-cli-service lint"
  },
But calling 'npm run hot' from the command line does not work.

**Comment by WolfgangAl** [comment]
First of all, it's a really bad idea to change anything inside `node_modules`. You should leave that to your package manager (npm I presume).

Second, the example isn't a very good starting point if you're looking to do extensive customization of dayspan-vuetify. In that  case, fork dayspan-vuetify and create a sample app that uses your own fork (you can also just fork dayspan-vuetify-example and change it to reference your own dayspan-vuetify fork). If, on the other hand, you're mainly looking to change some templates, look into the extensive collection of template points dayspan-vueitfy offers. dayspan-vuetify-example already has some examples where it customizes the default templates with its own. See `src\App.vue` in dayspan-vuetify-example, for example line 9 where the `title` template is overridden.

Third, before any changes in dayspan-vuetify source will be visible you have to rebuild dayspan-vuetify. Use `npm run build:lib` in the root of the dayspan-vuetify folder for this.

Last but no least: `hot` will watch your source folder, not node_modules. So any changes you make in node_modules will not be picked up. Any changes in your source folder however should be picked up and lead to a rebuild.

**Comment by connecteev** [comment]
@WolfgangAl thank you for the detailed response. I'll try this out.

**Comment by ClickerMonkey** [comment]
Thanks @WolfgangAl
