### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by upupupfly** [ClickerMonkey/dayspan-vuetify#186]
> That's cool! But there is no Chinese version. Thank you. 

我觉得这个东西太棒了，但是没有提供中文版，希望也能有简体中文语言以供选择呢，谢谢你，加油！

**Comment by ClickerMonkey** [comment]
Would you be willing to help out with that?

**Comment by mengyingzh** [comment]
> Would you be willing to help out with that?

I'd like to

**Comment by upupupfly** [comment]
> Would you be willing to help out with that?

I hope I can do something for this program ，but I’m afraid my English is not good enough .

**Comment by ClickerMonkey** [comment]
If anyone wants to add chinese support, please create a pull request for this project and https://github.com/ClickerMonkey/dayspan as they both need locale files to fully support a language.
