### ISSUE TITLE
NB: this.$dayspan.today.toMoment(...).locale is not a function

### ISSUE THREAD

**Issue by WolfgangAl** [ClickerMonkey/dayspan-vuetify#187]
This isn't so much an issue as a word of warning; when you build dayspan-vuetify in your project and upgrade its dependency dayspan to the newest version (^0.12.5) you will get numerous errors stating the 'locale' function is not available in Moment objects. This is because in dayspan moment was changed to a peer dependency. It will now use the moment version in dayspan-vuetify, which is locked at version 2.7.0 (devDependencies). The solution is to change the dev dependency for moment in dayspan-vuetify/package.json to read "^2.24.0" like this:
```
  "devDependencies": {
  ...
  "moment": "^2.24.0",
  ...
}
```

**Comment by ClickerMonkey** [comment]
The moment dependency will be removed on the next release, it was removed from the latest release of dayspan.
