### ISSUE TITLE
premonth event didn't show

### ISSUE THREAD

**Issue by mengyingzh** [ClickerMonkey/dayspan-vuetify#190]
when  I was in the view of month events on April, I tried to add an event to the 31th March. Then something strange just happened, the latest added event just disappeared but showed up when I moved to the view of month events on March. In another word, it seems that in the view of month, it doesn't show the other neighbor days events

**Comment by ClickerMonkey** [comment]
I tried to replicate the issue at https://clickermonkey.github.io/dayspan-vuetify/example/ but failed to. 

If you have a series of steps that allow me to reproduce the issue at the website above - please reopen and share them!
