### ISSUE TITLE
How to put day agenda into the side drawer where the date picker is?

### ISSUE THREAD

**Issue by Puddinglord** [ClickerMonkey/dayspan-vuetify#194]
I see where you can add the slide drawer as a slotted template and then you can add a date picker to it. I tried to add a ds-agenda-day to it but chrome is saying that not even the class is being put into the div. Is there something I am missing?

**Comment by ClickerMonkey** [comment]
That's not enough information at all to help you out, but you can use the slots `drawerTop`, `drawerPicker`, and `drawerBottom` for the sidebar.
