### ISSUE TITLE
How can I plot my existing data/events on calendar view

### ISSUE THREAD

**Issue by deepak-netwin** [ClickerMonkey/dayspan-vuetify#195]
Hi,

Can you please tell me how can I show my existing events on calendar editor. 
Also, what is the callback function to save events in database from calendar editor.

Thanks in advance.

**Comment by ClickerMonkey** [comment]
I don't know how your existing events are, but this library uses dayspan which has a Schedule object that defines when an event occurs.

https://github.com/ClickerMonkey/dayspan

This has information on events that are generated for loading/saving/deleting/etc:

https://github.com/ClickerMonkey/dayspan-vuetify/tree/master/docs#events
