### ISSUE TITLE
Create/Update iCalendar when new calendar event added in vuetify

### ISSUE THREAD

**Issue by deepak-netwin** [ClickerMonkey/dayspan-vuetify#197]
Hi,

I'm working on creation of [iCalendar](https://en.wikipedia.org/wiki/ICalendar) with standards RFC 2445. For this, I'm using this vuetify plugin to show calendar editor. With this, I'm able to create one day event without any issues.
For repeated events, I'm not getting  proper data from vuetify by which I can identify whether event in calendar editor is set as Annually/Monthly/Weekly etc. And due to this I can not create iCalendar string properly.

Can someone tell me, how can I get the re-occurrence period from calendar after adding/updating event. (FYI, I'm using these events for creation/updation of iCalendar at backend: event-create, event-update, event-remove etc.)

**Comment by ClickerMonkey** [comment]
The schedule defines how things repeat - you can also use Pattern to determine if a schedule matches a given Pattern. 

https://clickermonkey.github.io/dayspan/docs/classes/schedule.html
https://clickermonkey.github.io/dayspan/docs/classes/pattern.html#findmatch

I don't know anything about iCalendar/RFC2445 so I can't help you translate between that format and dayspan's.
