### ISSUE TITLE
weekdays and intervals

### ISSUE THREAD

**Issue by joaquinabenza** [ClickerMonkey/dayspan-vuetify#199]
Any chance to set up weekdays and intervals options such as this vuetify calendar example?
https://vuetifyjs.com/en/components/calendars#features

In week type its able to set custom intervals and weekdays

**Comment by ClickerMonkey** [comment]
I developed the Calendar in vuetifyjs, when I have the bandwidth or monetary incentive I'll be updating this library to use it.
