### ISSUE TITLE
How to remove some of the options from this plugin?

### ISSUE THREAD

**Issue by RidaNoor** [ClickerMonkey/dayspan-vuetify#200]
Hi there, 

Thankyou for this great Plugin!
I just wanna ask if I can remove the some features from this plugin? I mean I just want to display the pop-up and close it (Don't want editing. deletion or movement etc and all other features and options available), rather I just want to pop-up event , display details of the event and let it get closed, that's it. Is it possible? Plus, how can I add events to it? to which function/event?

Many thanks in advance.

**Comment by RidaNoor** [comment]
Just for more clarity, I want to event remove the options which appear when we click on 3 dots (appeared on event pop-up and option for editing). i dont want to display those options and completely remove them

**Comment by ClickerMonkey** [comment]
The huge majority of everything in this library is controllable by you, so your best bet is to use the Vue Chrome plugin, find the component, look at the code in the repo, and that tells you what determines what is seen. 

You can probably do it with props or passing values to the DayspanVuetify plugin. Check out this issue for info on how to pass values to that. https://github.com/ClickerMonkey/dayspan-vuetify/issues/203
