### ISSUE TITLE
Compatibility Internet Explorer

### ISSUE THREAD

**Issue by AudricCh** [ClickerMonkey/dayspan-vuetify#201]
Hello,

I was looking for a previous question about IE but I didn't find it, so I guess nobody are still using Internet Explorer :')
But I've got a problem : I've developped my application using your library (without Vuetify integration) but when I try to show it in IE, I've got a white page. I tryed to had babel polyfill, but it's always the same white page.

I wanna try your example to see if it was my application, but you've got the white page too.

What can I do to show up the component on IE ? Do you know any fix to resolve the problem ?

Thanks !

**Comment by BRafols** [comment]
Which IE version are you trying to use?

**Comment by AudricCh** [comment]
During my tests, it was IE 11

**Comment by ClickerMonkey** [comment]
I don't have any plans on supporting IE11 - but if you can get an example up and running in CodePen that doesn't work in IE and it includes the babel polyfill, vuetify, etc and there are no major console errors I can look into it. I can't help you without the console errors that are occurring. I can't know whether its a missing polyfill, Vuetify, Dayspan, DayspanVuetify, etc.
