### ISSUE TITLE
Occasionally the year sets back to 0 (1970) when you refresh the page or hit next

### ISSUE THREAD

**Issue by ClickerMonkey** [ClickerMonkey/dayspan-vuetify#34]

**Comment by ClickerMonkey** [comment]
Cannot reproduce again

**Comment by yuenlock** [comment]
I could reproduce it by choosing "Month" view and hitting refresh.
This will set the year back to 1970 and set the view to "Day".
It only happens when the view is set to "Month".

**Comment by ClickerMonkey** [comment]
Thank you! I was able to reproduce it again finally.

**Comment by ClickerMonkey** [comment]
Bug in dayspan, Calendar.toInput and Calendar.set were incompatible with `around`
