### ISSUE TITLE
type check failed for prop "calendar". Expected E, got Object.

### ISSUE THREAD

**Issue by zzAutumn** [ClickerMonkey/dayspan-vuetify#44]
`<template>
<div>
  <ds-calendar
  :calendar="calendar"
  >
  </ds-calendar>
</div>
</template>

<script>
import { Calendar, Weekday, Month, Sorts, Day } from 'dayspan';
import Vue from 'vue';

export default {
  name: 'dayspan',
  data () {
    return {
      calendar: Calendar.months()
    }
  },
  created () {
    
  }
  
}
</script>

<style scoped>

</style>`

I did like this, but I got wrong. how can I fix it?

**Comment by ClickerMonkey** [comment]
What does your JS file look like that calls `Vue.use( DayspanVuetify, ... )` ?

**Comment by ClickerMonkey** [comment]
(also, it's good to update to 0.2.1 - previous builds had some issues)

**Comment by ClickerMonkey** [comment]
Can you add this 
```
mounted() {
   window.console.log(this.calendar);
}
```

And take a screenshot of the output in the console?

**Comment by kelvinau** [comment]
Here they are:

![2018-08-04 11_09_14-devtools - localhost_8000_schedule](https://user-images.githubusercontent.com/5885902/43679236-e004eec4-97d6-11e8-8650-3c4dccbc6ca1.png)

![2018-08-04 11_10_03-devtools - localhost_8000_schedule](https://user-images.githubusercontent.com/5885902/43679242-f9a2093e-97d6-11e8-832c-054559c577cc.png)

**Comment by ClickerMonkey** [comment]
Thanks looks good. Either there are two versions of Dayspan being loaded (it might be accidentally packaged in the build of this project - but I didn't have this issue with my latest project) or the Vue version you have doesn't support this type of property validation.

What version of Vue are you working with?

**Comment by kelvinau** [comment]
Vue 2.5.2, Vuetify 1.1.9, dayspan-vuetify 0.2.1
I even tried to create a fresh project with vue-init webpack, and yarn add vuetify dayspan-vuetify. Still got the same error.

**Comment by kelvinau** [comment]
Have spent half a day to debug this, but still don't have any clues of the issue.
`console.log(Calendar.months() instanceof Calendar);` returns True, but somehow when I pass `Calendar.months()` as a property, it becomes not an instance of `Calendar` anymore. 

For a quick work-around on setting up the example (https://github.com/ClickerMonkey/dayspan-vuetify#full-example), you can simply not provide the property to `ds-calendar-app`, as its default is `Calendar.months()` already. `savestate` triggered by change event contains the latest calendar instance, so I can just do this:
![2018-08-04 17_11_51-schedule vue - school-course - visual studio code](https://user-images.githubusercontent.com/5885902/43681475-895f4514-9809-11e8-9617-90dc3c6d893d.png)

**Comment by ClickerMonkey** [comment]
If you can, share your code with me so I can try it out myself - it could be the way something is configured.

**Comment by ClickerMonkey** [comment]
If anyone could supply a zip of their project (or a minimal amount of code that still has the issue) that would help immensely!

I'm thinking it has something to do with webpack configuration.

**Comment by dnasir** [comment]
Here's a test app that demonstrates this problem. Built using the GUI that came with `@vue/cli` version `3.0.0-rc.10`.

Hope this helps.

[test-app.zip](https://github.com/ClickerMonkey/dayspan-vuetify/files/2260611/test-app.zip)

**Comment by ClickerMonkey** [comment]
Webpack likes to package all dependencies into the built files - and it is not straight forward to exclude them.

Version 0.2.2 was published to NPM and I've test and verified that it is working fine now.

Feel free to open this back up if that is no longer the case @dnasir @kelvinau & @zzAutumn .

**Comment by dnasir** [comment]
I can confirm that this bug has been fixed. Awesome work!
