### ISSUE TITLE
Relative font imports do not work

### ISSUE THREAD

**Issue by jeffbaumes** [ClickerMonkey/dayspan-vuetify#45]
Following the install instructions, I get errors that `.fonts/*.woff` etc. are not found from `*.css.min`. I was able to work around this by copying the `fonts` directory into the `lib` directory so that the relative imports line up. Should the imports in the `.min.css` be changed to `../fonts/*.woff` etc. or am I doing something wrong on how I import it?

**Comment by ClickerMonkey** [comment]
Nope you're not doing anything wrong, that build version is not proper.
Update to 0.2.1 and it should work fine. Look at the example in the readme
to see how to also import the fonts and css from Vuetify.

In older builds the fonts and css from Vuetify we're being included in the
build but should not have been.

**Comment by ClickerMonkey** [comment]
If you are still having problems with the newest version feel free to open this issue back up, thanks.
