### ISSUE TITLE
Dragging to create event does not work in Firefox 

### ISSUE THREAD

**Issue by developernaren** [ClickerMonkey/dayspan-vuetify#47]
Tested On:
Browser: Firefox 61.0.1
OS : Ubuntu 18.04 and Ubuntu 16.04 (64-bit)

When I drag on multiple cells, it just opens the dialog to create an event on the day I started to drag the mouse from. It works like a click event.

This works in chrome (68.0.344). It opens a modal with multiple day selected, as expected.

Please let me know if you need additional information to replicate the issue.

**Comment by ClickerMonkey** [comment]
Version 0.2.4 published with Firefox fix.

Firefox requires a `user-select: none` on any element you start "dragging" on so it knows to trigger mousemove (because while you're selecting text FF doesn't like to trigger mousemove).
