### ISSUE TITLE
Clicking on a day results in page navigation

### ISSUE THREAD

**Issue by dnasir** [ClickerMonkey/dayspan-vuetify#48]
Clicking on a day in month view results in a page navigate. Since there's no URL set as the `href` value, it simply reloads the page.

Adding the `.prevent` modifier to the `a` tag in the `Day.vue` component should fix this problem.

**Comment by ClickerMonkey** [comment]
Release 0.2.3 includes the prevent modifier, thank you!

Not sure why it wasn't happening for me in my example, thanks.
