### ISSUE TITLE
Not sure how to customize

### ISSUE THREAD

**Issue by developernaren** [ClickerMonkey/dayspan-vuetify#50]
I am looking to customize calendar. I need to add and remove some fields in the create event pop up and load event when the calendar starts, But it is not mentioned anywhere in the doc and am very confused.

Are there any docs or links I can get started on?

You can publish the code you are using for the [example](https://clickermonkey.github.io/dayspan-vuetify/example/) somewhere, that can be helpful to me.

**Comment by ClickerMonkey** [comment]
When in doubt, the code is your friend!

There are a couple different ways to do what you want to do depending on precisely what you want to do.

1. If you want all "location" inputs and displays hidden you do this:
```typescript
Vue.use( DaySpanVuetify, {
  data: {
    supports: {
      location: false
    }
  }
});
```
(checkout [this](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/component.js#L41) to see global event detail stuff)

2. If you want "location" inputs on all create popover to be hidden...
```typescript
Vue.use( DaySpanVuetify, {
  data: {
    defaults: {
      dsCalendarEventCreatePopover: {
        prompts: { location: false }
      }
    }
  }
});
```
(checkout [this](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/defaults.js#L145) for defaults on that component that you can specify as props or override globally)

3. If you want to do it for a specific popover you can use the props
```vue
<ds-calendar-event-create-popover
  :prompts="{location: false}"
></ds-calendar-event-create-popover>
```
(checkout [here](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarEventCreatePopover.vue#L264))

4. If you wish to override the input for the location field there's a scoped slot for that:
```vue
<ds-calendar-event-create-popover>
<div slot="eventCreatePopoverLocation" slot-scope="{ details }">
  <v-text-field
    single-line hide-details solo flat full-width
    label="Where dis at?"
    v-model="details.location"
  ></v-text-field>
</div>
</ds-calendar-event-create-popover>
```
(checkout [here](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarEventCreatePopover.vue#L79))

5. If you wish to add a new field:

```vue
<ds-calendar-event-create-popover>
<div slot="eventCreatePopoverBodyBottom" slot-scope="{ details, calendarEvent, calendar }">
   Here are some new fields!
</div>
</ds-calendar-event-create-popover>
```
(checkout [here](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarEventCreatePopover.vue#L197))

You can basically do that for all event details.

**Comment by developernaren** [comment]
I am getting a `Missing required prop: "calendarEvent"` in example 5 that you gave. What should I pass on to "calendarEvent" prop in `ds-calendar-event-create-popover` component.

**Comment by ClickerMonkey** [comment]
The above code samples are not complete pieces of code. I'm just showing where things are placed relatively speaking. 

Checkout [this](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/app.vue#L27) file to see where the create popover is specified.

You add props and slots in there.

**Comment by developernaren** [comment]
I am slowly getting a hang of this. Slots and scopes were new to me. So learning new things. I  am stuck with this one.

![dayspan schedule actions](https://user-images.githubusercontent.com/3628468/44224685-e8614080-a1aa-11e8-9400-2241a7666aa6.png)

https://github.com/ClickerMonkey/dayspan-vuetify/blob/88f3b72e8abd66755cd5bb3182fbcef65b20db18/src/components/CalendarEventPopover.vue#L35-L47

I want to change the labels and actions of these buttons but in this particular part of the component, there are no named slots that I can replace. How can I add different labels and attach action to clicks on those options. Appreciate the help!

**Comment by ClickerMonkey** [comment]
As you can see here:

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/Event.vue#L42

You can specify the scheduleActions slot and add your own

Once you override that, I imagine you'll want to specify a Menu like done in ds-schedule-actions:

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/ScheduleActions.vue#L3

**Comment by ClickerMonkey** [comment]
There is a slot named `eventPopoverToolbarActions` that you can override inside your `<ds-calendar-event-popover>` definition.

**Comment by ClickerMonkey** [comment]
Found here:

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarEventPopover.vue#L31

**Comment by developernaren** [comment]
It did not override anything. It just shows up next to the 'action dots'. 
```
<template slot="eventPopover" slot-scope="slotData">
                <ds-calendar-event-popover
                        v-bind="slotData"
                        @finish="saveState"
                >


                    <template slot="eventPopoverToolbarActions" slot-scope="slotData">
                        hello world
                    </template>

                </ds-calendar-event-popover>
            </template>`
`
![hello world](https://user-images.githubusercontent.com/3628468/44225521-7807ee80-a1ad-11e8-81b2-4de03df301d9.png)
I used this code.

**Comment by developernaren** [comment]
The `schedule-actions` is not inside the slot. is that the issue? They are two different tags.

**Comment by developernaren** [comment]
I am having issue closing the detail pop up now.
```
<template slot="eventPopover" slot-scope="slotData">
            <v-btn @click.native="close">Close</v-btn>
</template>
```
I just want to close the eventPopover on clicking the button. But not sure how.

**Comment by ClickerMonkey** [comment]
You have one object in slotData, so you can either extract the variables you want from slotData, or reference it like so:

```vue
<template slot="eventPopover" slot-scope="slotData">
            <v-btn @click.native="slotData.close">Close</v-btn>
</template>
```
OR
```vue
<template slot="eventPopover" slot-scope="{ close }">
            <v-btn @click.native="close">Close</v-btn>
</template>
```

See this for more info on scoped slots: https://vuejs.org/v2/guide/components-slots.html#Destructuring-slot-scope

**Comment by ClickerMonkey** [comment]
Also the eventPopoverToolbarActions problem above was fixed - I don't recall who (could've been you) pointed out an error in the HTML.

It's easy to loose track of the stuff you post in here since its a closed issue.

**Comment by developernaren** [comment]
Yeah, that was me. I created a PR. Thanks for the quick response.
