### ISSUE TITLE
Help pls.. dayspan  UI and i can't click the day dropdown menu

### ISSUE THREAD

**Issue by robrodriguez** [ClickerMonkey/dayspan-vuetify#51]
![dayspan](https://user-images.githubusercontent.com/16813664/43872703-98196f58-9bb5-11e8-9e03-3efa8eb45fbf.PNG)

**Comment by ClickerMonkey** [comment]
That looks so horribly mangled!

What browser & version?

Which versions for the other libraries?

Did you pull in all the styling for Vuetify and dayspan-vuetify?

**Comment by ClickerMonkey** [comment]
I just created an example/template repo which should have everything working as expected:

https://github.com/ClickerMonkey/dayspan-vuetify-example

I will close this issue in a few days if I don't get a response.

Thank you!

**Comment by robrodriguez** [comment]
hi. here's my code.

**Comment by robrodriguez** [comment]
<template>
  <v-layout pt-5 mt-5  >
    <ds-calendar-app :calendar="calendar"></ds-calendar-app>
  </v-layout>
</template>

<script>
import { Calendar } from 'dayspan';

export default {
  name: 'app',
  data: () => ({
    calendar: Calendar.months()
  })
}
</script>

**Comment by robrodriguez** [comment]
![5](https://user-images.githubusercontent.com/16813664/43940842-193ce68e-9ca4-11e8-8dca-374279475552.PNG)

**Comment by robrodriguez** [comment]
![6](https://user-images.githubusercontent.com/16813664/43940895-62293992-9ca4-11e8-8ec9-a8d6be423e9f.PNG)

**Comment by robrodriguez** [comment]
thank you sir.!

**Comment by ClickerMonkey** [comment]
Make sure you are using Vuetify >= 1.1.9**

You are also putting the `<ds-calendar-app>` in a layout - which might be causing issues. Try to avoid that, and if you can't try ensuring that the height of every outer element is maxed out (ie 100% when possible)

**Comment by ClickerMonkey** [comment]
I'm closing for now due to lack of response, please reopen if you are still experiencing this problem!
