### ISSUE TITLE
Bug related on annually schedule event on 5th week of...

### ISSUE THREAD

**Issue by menteora** [ClickerMonkey/dayspan-vuetify#52]
Hi @ClickerMonkey, 
  great work! Awesome components!

I'll start study your library.

There is a small bug, not related to your application, but related to schedule in general.

If I create annually event that repeats on 5th week, is not guarantee next year have 5 weeks.

For example, I set annual schedule on 5th sunday of July 2018, 5th sunday of July 2019 not exist and event will not created.

July 2018

![image](https://user-images.githubusercontent.com/3657745/43894010-248ac930-9bd1-11e8-807d-7c9166034d34.png)

July 2019

![image](https://user-images.githubusercontent.com/3657745/43894106-6a620216-9bd1-11e8-8c49-59ad73dc4b4f.png)

Probably you can solve problem with:
"1st sunday of July 2018"
"2nd sunday of July 2018"
"3rd sunday of July 2018"
"4th sunday of July 2018"
"5th or last sunday of July 2018"

**Comment by ClickerMonkey** [comment]
Thanks for the suggestion!

Unfortunately the "patterns" in DaySpan don't work like that (using OR logic). BUT there is a pattern for "Last `weekday` in `month`".

This pattern is not in the list when defining an event schedule, but can easily be turned on.
