### ISSUE TITLE
Back button support on mobile

### ISSUE THREAD

**Issue by gedw99** [ClickerMonkey/dayspan-vuetify#55]
At the moment the browser or mobile button is not handled properly.
 Instead the code relies on back buttons in the actual GUI.

This is really not a great user experience.

I did some digging about hardware back button support in vuejs. It's using a pretty easy to understand pop and push approach so it should be reasonably easy to support.

See here :

https://stackoverflow.com/questions/41558132/vue-js-push-and-the-back-button

**Comment by ClickerMonkey** [comment]
I think this is the responsibility of a router, so I wouldn't put that sort of code in this library - it's too specific (perhaps could be made generic enough, not sure at the moment).

I should create an example though which links a calendar with the routing. I'll create an issue for that.

**Comment by gedw99** [comment]
thanks
