### ISSUE TITLE
Event for when an Event is clicked in week view

### ISSUE THREAD

**Issue by sonoftheweb** [ClickerMonkey/dayspan-vuetify#57]
Hi,

Very nice implementation you have going here. I figured out a way to use it in my app. I also figured out a way to redirect instead of opening a modal. However this works on all views but the week view. For some reason I am unable to figure out what event is fired when a schedule is clicked in the week view (via ds-calendar) in 

`<ds-calendar ref="calendar"
                                         v-bind="{$scopedSlots}"
                                         v-on="$listeners"
                                         :calendar="calendar"
                                         @edit="edit"
                                         @mouse-down-event="testFunction"
                                         @view-day="viewDay"
                            ></ds-calendar>`

Is there anything I am missing here? 

EDIT

No matter what I do "mouse-down-event" does not seem to fire in week view on my implementation.

**Comment by ClickerMonkey** [comment]
As you can see here:

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/Event.vue#L42

You can specify the `scheduleActions` slot and add your own

Once you override that, I imagine you'll want to specify a Menu like done in `ds-schedule-actions`:

https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/ScheduleActions.vue#L3
