### ISSUE TITLE
Use <ds-calendar-app> in container

### ISSUE THREAD

**Issue by hieu-brain** [ClickerMonkey/dayspan-vuetify#59]
Please tell me how to use the `<v-navigation-drawer>` without using `<v-toolbar>` and `<ds-calendar-app>`?
I want to import the `<ds-calendar-app>` content into the page content that has the layout available.

**Comment by ClickerMonkey** [comment]
You could copy [the ds-calendar-app](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarApp.vue) component and take out what you don't want.

You could also just use the `ds-calendar` component, which doesn't have the toolbar or side menu.

**Comment by ClickerMonkey** [comment]
I'm closing this, please reply if you're still having problems and I could open this back up with more information.

**Comment by deep0410** [comment]
Use <ds-calendar-app> in container that isn't the main "#app"
I want to use the entire application not just the calendar

**Comment by gowrisankarvoltuswave** [comment]
Hi I am using calendarApp component since 2 years, And I am using this feature very rarely. Today i opened this and i got this  error "TypeError: this.$dsDefaults is not a function" can you help me on this. This function called from calendarApp props.
