### ISSUE TITLE
How to set another first day of the week?

### ISSUE THREAD

**Issue by webwakko** [ClickerMonkey/dayspan-vuetify#60]
Hi,

i've been searching the code to found the settings for week or month view.
More in particular, how to set the first day of the week to a monday instead of a sunday?

**Comment by mannro** [comment]
Before init DaySpanVuetify plugin set moment.js to your desired locale. 
e.g.

momentLocale.js
```
import moment from 'moment'
moment.locale('sk')
```

then in DaySpanVuetify plugin init
```
Vue.use(DaySpanVuetify, {
    data: {
        defaults: {
            dsWeeksView: {
                weekdays: moment.weekdaysShort(true)
            },...
```

**Comment by ClickerMonkey** [comment]
If @mannro 's code works, that's great!

Better configuration for which days show in a week - and which day is the first day - will be added at some unknown point in the future. 

I'm working on a Vuetify calendar component which has this functionality and it will be available there before here.

**Comment by mtx-z** [comment]
@mannro I can't get monday as first day using your code. Is it still working under 0.3.6 ? 
thanks!

**Comment by ClickerMonkey** [comment]
It can't be done yet

**Comment by mtx-z** [comment]
neither for MonthView nor DayView?

**Comment by ClickerMonkey** [comment]
For any view

**Comment by mtx-z** [comment]
As @mannro said, when I checkout the dayspan-vuetify demo I'm able to correctly change the entire locale, and to change the first day of the week with monday: 

By changing main.js to:


```
import Vue from 'vue'
import Vuetify from 'vuetify'
import DaySpanVuetify from 'dayspan-vuetify'
import App from './App.vue'
import dsFr from 'dayspan-vuetify/src/locales/fr';
import moment from 'moment'
import 'moment/locale/fr';
import 'vuetify/dist/vuetify.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'dayspan-vuetify/dist/lib/dayspan-vuetify.min.css'

Vue.config.productionTip = false
moment.locale('fr');

Vue.use(Vuetify);

Vue.use(DaySpanVuetify, {
  methods: {
    getDefaultEventColor: () => '#1976d2'
  }
});

Vue.$dayspan.addLocale('fr', dsFr);
Vue.$dayspan.setLocale('fr', true);

new Vue({
  el: '#app',
  render: h => h(App)
})

```

But I'm still not able to use it in my own project. Only thing that change from my project is the `render: h => h(App)` in the `new Vue()`
![capture](https://user-images.githubusercontent.com/2423235/48302203-b1749f80-e4f9-11e8-8186-237db29a75f0.PNG)

**Comment by scoutrul** [comment]
Monday for first day of week in monthly calendar is prop :weekdays="[1, 2, 3, 4, 5, 6, 0]"

**Comment by JeppePepp** [comment]
:weekdays="[1, 2, 3, 4, 5, 6, 0]"
