### ISSUE TITLE
Custom click action on events working on day view and not on week view

### ISSUE THREAD

**Issue by sonoftheweb** [ClickerMonkey/dayspan-vuetify#61]
I saw your reply, but I believe I did not explain much of what I was trying to do.

I have a web app using Vuetify and all I needed was the calendar part <ds-calendar>. One of the changes made was to disable ability to add events to the calendar as events are pulled from a database and used to populate the calendar. On clicking at an event, it should redirect the user to a page with related information. For this, I use the "edit" event (@edit="edit"). However, I do not get the same event when I click on the event in the week view. I recently downloaded the example code and did a trace to see which even is fired on the week view and quickly found that the event fired "mouse-down-event", which would carry the event object in it's payload, was not fired as implemented in my application. 

I saw your reply on my previous issue but I am looking to redirect to the details page. when clicking on the events in week view, I need to have access to that event. It is to be noted that I based my component on the codes in CalendaApp.vue since I am not using the extra scaffolding.  See the codes below...

`<template>
    <v-container fluid fill-height>
        <v-layout row wrap>
            <v-flex xs12 md3 class="pr-4">
                <v-card class="pa-2 mb-3">
                    <slot name="view"
                          :currentType="currentType"
                          :types="types">

                        <v-menu>
                            <v-btn flat slot="activator">
                                {{ currentType.label }}
                                <v-icon>arrow_drop_down</v-icon>
                            </v-btn>
                            <v-list>
                                <v-list-tile v-for="type in types"
                                             :key="type.id"
                                             @click="currentType = type">
                                    <v-list-tile-content>
                                        <v-list-tile-title>{{ type.label }}</v-list-tile-title>
                                    </v-list-tile-content>
                                    <v-list-tile-action>{{ type.shortcut }}</v-list-tile-action>
                                </v-list-tile>
                            </v-list>
                        </v-menu>

                    </slot>
                </v-card>
                <v-card class="pa-2 mb-3">
                    <slot name="today"
                          :setToday="setToday"
                          :todayDate="todayDate"
                          :calendar="calendar">

                        <v-tooltip bottom>
                            <v-btn slot="activator"
                                   class="ds-skinny-button"
                                   depressed
                                   :icon="$vuetify.breakpoint.smAndDown"
                                   @click="setToday">

                                
                                <span v-if="$vuetify.breakpoint.mdAndUp">{{ todayLabel }}</span>
                                <v-icon v-else>{{ labels.todayIcon }}</v-icon>

                            </v-btn>
                            <span>{{ todayDate }}</span>
                        </v-tooltip>

                    </slot>
                    <slot name="prev"
                          :prev="prev"
                          :prevLabel="prevLabel"
                          :calendar="calendar">

                        <v-tooltip bottom>
                            <v-btn slot="activator"
                                   icon depressed class="ds-light-forecolor ds-skinny-button"
                                   @click="prev">
                                <v-icon>keyboard_arrow_left</v-icon>
                            </v-btn>
                            <span>{{ prevLabel }}</span>
                        </v-tooltip>

                    </slot>
                    <slot name="next"
                          :next="next"
                          :nextLabel="nextLabel"
                          :calendar="calendar">

                        <v-tooltip bottom>
                            <v-btn slot="activator"
                                   icon depressed
                                   class="ds-light-forecolor ds-skinny-button"
                                   @click="next">
                                <v-icon>keyboard_arrow_right</v-icon>
                            </v-btn>
                            <span>{{ nextLabel }}</span>
                        </v-tooltip>

                    </slot>
                    <slot name="summary"
                          :summary="summary"
                          :calendar="calendar">

                        <span class="tayo-card-title">
                            {{ summary }}
                        </span>

                    </slot>
                </v-card>
                <v-card class="mb-3 hidden-sm-and-down">
                    <slot name="drawerPicker" :calendar="calendar" :picked="rebuild">
                        <div class="pa-3" v-if="calendar">
                            <ds-day-picker :span="calendar.span" @picked="rebuild"></ds-day-picker>
                        </div>
                    </slot>
                </v-card>
            </v-flex>
            <v-flex xs12 md9>
                <ds-gestures
                        @swipeleft="next"
                        @swiperight="prev">

                    <div v-if="currentType.schedule" class="ds-expand">

                        <slot name="calendarAppAgenda"
                              v-bind="{$scopedSlots, $listeners, calendar, edit, viewDay}">

                            <ds-agenda
                                    v-bind="{$scopedSlots}"
                                    v-on="$listeners"
                                    :calendar="calendar"
                                    @edit="edit"
                                    @view-day="viewDay"
                            ></ds-agenda>

                        </slot>

                    </div>

                    <div v-else class="ds-expand">

                        <slot name="calendarAppCalendar"
                              v-bind="{$scopedSlots, $listeners, calendar, edit, viewDay}">

                            <ds-calendar ref="calendar"
                                         v-bind="{$scopedSlots}"
                                         v-on="$listeners"
                                         :calendar="calendar"
                                         @edit="edit"
                                         @view-day="viewDay"
                                         :handle-add="false"
                                         :handle-move="false"
                            ></ds-calendar>
                            

                        </slot>

                    </div>

                </ds-gestures>

                <slot name="containerInside" v-bind="{events, calendar}"></slot>
            </v-flex>
        </v-layout>
    </v-container>
</template>`

`export default {

        name: 'dsCalendarApp',

        props:
            {
                events: {
                        type: Array
                },
                calendar: {
                    type: Calendar,
                    default() {
                        return Calendar.months();
                    }
                },
                types: {
                    type: Array,
                    default() {
                        //return this.$dsDefaults().types;
                        return [
                            {id: 'D', label: __('messages.calendar_day'),     shortcut: __('messages.calendar_day_short'), type: Units.DAY,   size: 1,  focus: 0.4999, repeat: true,  listTimes: true,  updateRows: true,  schedule: false },
                            {id: 'W', label: __('messages.calendar_week'),    shortcut: __('messages.calendar_week_short'), type: Units.WEEK,  size: 1,  focus: 0.4999, repeat: true,  listTimes: true,  updateRows: true,  schedule: false },
                            {id: 'M', label: __('messages.calendar_month'),   shortcut: __('messages.calendar_month_short'), type: Units.MONTH, size: 1,  focus: 0.4999, repeat: true,  listTimes: false, updateRows: true,  schedule: false },
                            {id: 'Y', label: __('messages.calendar_year'),    shortcut: __('messages.calendar_year_short'), type: Units.YEAR,  size: 1,  focus: 0.4999, repeat: true,  listTimes: false, updateRows: true,  schedule: false },
                            {id: 'S', label: __('messages.calendar_schedule'),shortcut: __('messages.calendar_schedule_short'), type: Units.DAY,   size: 92, focus: 0.0000, repeat: false, listTimes: false, updateRows: false, schedule: true },
                            {id: 'X', label: __('messages.calendar_four_days'),  shortcut: 'X', type: Units.DAY,   size: 4,  focus: 0.4999, repeat: true,  listTimes: true,  updateRows: true,  schedule: false }
                        ];
                    }
                },
                allowsAddToday: {
                    type: Boolean,
                    default() {
                        return this.$dsDefaults().allowsAddToday;
                    }
                },
                formats: {
                    validate(x) {
                        return this.$dsValidate(x, 'formats');
                    },
                    default() {
                        return this.$dsDefaults().formats;
                    }
                },
                labels: {
                    validate(x) {
                        return this.$dsValidate(x, 'labels');
                    },
                    default() {
                        return this.$dsDefaults().labels;
                    }
                },
                styles: {
                    validate(x) {
                        return this.$dsValidate(x, 'styles');
                    },
                    default() {
                        return this.$dsDefaults().styles;
                    }
                },
                optionsDialog: {
                    validate(x) {
                        return this.$dsValidate(x, 'optionsDialog');
                    },
                    default() {
                        return this.$dsDefaults().optionsDialog;
                    }
                },
                promptDialog: {
                    validate(x) {
                        return this.$dsValidate(x, 'promptDialog');
                    },
                    default() {
                        return this.$dsDefaults().promptDialog;
                    }
                },
                defaultEvents: {
                    type: Array,
                    default() {
                        return [];
                    }
                }
            },

        data: vm => ({
            drawer: null,
            currentType: vm.types[2],
            optionsVisible: false,
            options: [],
            promptVisible: false,
            promptQuestion: '',
            promptCallback: null,
            todayLabel: __('messages.calendar_today')
        }),
        watch: {
            'currentType': 'tryRebuild',
            'events': 'applyEvents',
            'calendar': 'applyEvents'
        },
        computed: {
            summary() {
                let small = this.$vuetify.breakpoint.xs;
                if (small) {
                    return this.calendar.start.format(this.formats.xs);
                }
                let large = this.$vuetify.breakpoint.mdAndUp;
                return this.calendar.summary(false, !large, false, !large);
            },
            todayDate() {
                return this.$dayspan.today.format(this.formats.today);
            },
            nextLabel() {
                //return this.labels.next(this.currentType);
                return __('messages.calendar_next');
            },
            prevLabel() {
                //return this.labels.prev(this.currentType);
                return __('messages.calendar_previous');
            },
            hasCreatePopover() {
                return !!this.$scopedSlots.eventCreatePopover;
            },
            getScrollbarWidth() {
                return window.innerWidth - document.documentElement.clientWidth;
            }
        },

        mounted() {
            this.setState({events: this.defaultEvents});
            if (!this.$dayspan.promptOpen) {
                this.$dayspan.promptOpen = (question, callback) => {
                    this.promptVisible = false;
                    this.promptQuestion = question;
                    this.promptCallback = callback;
                    this.promptVisible = true;
                };
            }
        },
        methods: {
            setState(state) {
                state.eventSorter = state.listTimes
                    ? Sorts.List([Sorts.FullDay, Sorts.Start])
                    : Sorts.Start;

                this.calendar.set(state);
                this.updateType();
                this.triggerChange();
            },
            tryRebuild(newType) {
                this.rebuild();
            },
            updateType() {
                let foundType = this.types.find((type) =>
                    type.type === this.calendar.type &&
                    type.size === this.calendar.size
                );

                if (foundType) {
                    this.currentType = foundType;
                }
            },
            applyEvents() {
                if (this.events) {
                    this.calendar.removeEvents();
                    this.calendar.addEvents(this.events);
                }
            },
            isType(type, aroundDay) {
                let cal = this.calendar;

                return (cal.type === type.type && cal.size === type.size &&
                    (!aroundDay || cal.span.matchesDay(aroundDay)));
            },
            rebuild(aroundDay, force, forceType) { //okay. Sure. Thanks. Bye
                let type = forceType || this.currentType || this.types[2];

                if (this.isType(type, aroundDay) && !force) {
                    return;
                }

                let input = {
                    type: type.type,
                    size: type.size,
                    around: aroundDay,
                    eventsOutside: true,
                    listTimes: type.listTimes,
                    updateRows: type.updateRows,
                    updateColumns: type.listTimes,
                    fill: !type.listTimes,
                    otherwiseFocus: type.focus,
                    repeatCovers: type.repeat
                };

                this.setState(input);
            },
            next() {
                this.calendar.unselect().next();

                this.triggerChange();
            },
            prev() {
                this.calendar.unselect().prev();

                this.triggerChange();
            },
            setToday() {
                this.rebuild(this.$dayspan.today);
            },
            viewDay(day) {
                this.rebuild(day, false, this.types[0]);
            },
            edit(calendarEvent) {
                window.location.href = calendarEvent.data.link;
            },
            triggerChange() {
                this.$emit('change', {
                    calendar: this.calendar
                });
            }
        }
    }
</script>`

**Comment by ClickerMonkey** [comment]
That's very interesting, I will look into it!
