### ISSUE TITLE
Translation recommendations.

### ISSUE THREAD

**Issue by sonoftheweb** [ClickerMonkey/dayspan-vuetify#62]
Hi again, 

I had some luck translating most of the text used on the calendar, good times. However I noticed that the days and months are all generated by moments.js which also supports locale. On my current project, we do translation a little different from what is mostly expected, but we can get the locales from the backend. 

I would suggest that there be a key (or prop) by which we can define locale to be used, which gets passed down to when moments generates the days and month names for that specific locale.

**Comment by ClickerMonkey** [comment]
Thanks for the recommendations, I'll make a comment and do the work in #54

**Comment by ClickerMonkey** [comment]
Just a heads up - locale support is in the latest commit and will be in the next release (soon):

https://github.com/ClickerMonkey/dayspan-vuetify/commit/ec63896aadb4a889cef981091ab55998b7c0fc8f
