### ISSUE TITLE
Week view headers and body misaligned.

### ISSUE THREAD

**Issue by sonoftheweb** [ClickerMonkey/dayspan-vuetify#63]
I noticed that the headers in the week view are a bit misaligned from the body. I think I may have a quick fix to that.

Since we cannot for sure state what the width of a scroll bar on any random browser on any random computer is, I suggest we measure this out: 

```
getScrollbarWidth() {
                return window.innerWidth - document.documentElement.clientWidth;
            }
```

With this we can add a padding to the row in the header to replicate something like this:

`<div class="ds-week-header" v-bind:style="{ padding-right: getScrollbarWidth() + 'px' }"> ... </div>`

**Comment by ClickerMonkey** [comment]
What browser did you experience this in?

**Comment by sonoftheweb** [comment]
All test were done in Google Chrome Version 68.0.3440.106 for Linux (Ubuntu)

**Comment by sonoftheweb** [comment]
Here are some images to support.

![screenshot from 2018-08-21 01-43-55](https://user-images.githubusercontent.com/1128096/44374265-4cef0900-a4e5-11e8-9988-fa99a312ec72.png)
![screenshot from 2018-08-21 01-42-55](https://user-images.githubusercontent.com/1128096/44374266-4cef0900-a4e5-11e8-9489-e994ce547b50.png)

**Comment by sonoftheweb** [comment]
The first image is with me using the quick fix: since I noticed that the scroll bar on the calendar body is 15px, I added  a padding to the right to shift all headers to the left just enough so they align.

**Comment by webwakko** [comment]
The same occurs also in the 4 day view...

**Comment by webwakko** [comment]
I applied the fix but had to tweak it a little bit.
For some reason padding-right was not working for me, so I had to use the DOM way and added it like this <div class="ds-week-header" v-bind:style="{ paddingRight: getScrollbarWidth() + 'px' }">
I've added the getScrollbarWidth to the methods part of weekheader.vue and it works for both week & 4 days view.

**Comment by webwakko** [comment]
Noticed that with the fix from @sonoftheweb there is still a little thing that is off.. 
![image](https://user-images.githubusercontent.com/6866229/44388947-d3c5d500-a529-11e8-9c8f-430b10b62ef9.png)
The planned items that cover more than 1 day are not well aligned the next day.

**Comment by ClickerMonkey** [comment]
Thanks for looking into this! The scrollbar really messes with things, I'll work on a fix
