### ISSUE TITLE
Unable to resize planned items or move/drag them to another timeslot

### ISSUE THREAD

**Issue by webwakko** [ClickerMonkey/dayspan-vuetify#64]
I noticed 2 little "bugs" (if I may call them bugs)... 

1. when trying to move an item to another time on the same date, it jumps back to the original timeslot. When moving to another day, the popup to confirm or cancel the move is shown.

2. when trying to resize a planned item to cover a bigger timeslot, it drags instead of resizing. Not sure if this is a bug or a feature that has not been implemented yet

**Comment by ClickerMonkey** [comment]
1. Thanks, I'll look into it.

2. Resizing is not currently supported.

**Comment by wolfy007** [comment]
Hello!

Is there any idea about this or any solution? :)
