### ISSUE TITLE
[Help wanted] : Best practice init configuration

### ISSUE THREAD

**Issue by liliputien** [ClickerMonkey/dayspan-vuetify#66]
Hi,

What is the best practice for init configuration about firstday of week (for exemple, in my contry first day id monday). And how configure the default display view (by default is by month, and I want to show by default by week).

Thanks.

**Comment by ClickerMonkey** [comment]
At the moment first day of week is not configurable. I don't have plans anytime soon to add it to this library (I will eventually).

I'm working on a calendar component in Vuetify that has this functionality fully configurable. That will be available before it's added to this library.

**Comment by liliputien** [comment]
Thanks for reply, and good luck. Really good library ;)
