### ISSUE TITLE
[Help wanted] Get event saved

### ISSUE THREAD

**Issue by liliputien** [ClickerMonkey/dayspan-vuetify#67]
Hi,

I don't understand in documentation how can I bind the event's save method for editing and update event ....

I hability to bind the events's create method (in eventCreatePopover) .....

This is a great bookstore that you offer. It may be missing just a little documentation and example. Very good job

**Comment by ClickerMonkey** [comment]
There are a few events you can list to at the `ds-calendar` or `ds-calendar-app` level:

https://github.com/ClickerMonkey/dayspan-vuetify/tree/master/docs#events

**Comment by liliputien** [comment]
Thanks, I'm an idiot.....

Documentation explain exactely what we need to do ...
