### ISSUE TITLE
Rendering all events on all days

### ISSUE THREAD

**Issue by iamgoddog** [ClickerMonkey/dayspan-vuetify#68]
Hi, I'm loading events with this method:
``` 
          let state = {
            events: time_entries.map( ev => {
              return {
                data: Vue.util.extend( this.$dayspan.getDefaultEventDetails(), {
                  title: ev.project.name
                }),
                schedule: {
                  start: Day.fromMoment( moment( ev.spent_date, "YYYY-MM-DD" ) ),
                  duration: ev.hours,
                  durationUnit: 'hours'
                }
              };
            }),
            preferToday: false
          };
          this.$refs.app.setState(state);
``` 

What happens is that all events render on every day in the view. I've debugged and verified that start is indeed a valid moment holding `ev.spent_date`.

Is there some other field necessary in the schedule definition when using `start`? 

Am I missing something or is this a bug?

**Comment by ClickerMonkey** [comment]
Start and end in schedule allow you to provide a restricted span of time for repeatable events.

It doesn't look like you have a repeatable event so perhaps looking using a schedule function:

https://github.com/ClickerMonkey/dayspan/blob/master/src/Schedule.ts#L1832

Basically your schedule you definded occurs everyday starting on the given day. You have to specify more restrictions (like month, or day of month, etc) to make it repeat less.
