### ISSUE TITLE
Incorrect initial currentType value

### ISSUE THREAD

**Issue by WolfgangAl** [ClickerMonkey/dayspan-vuetify#69]
`currentType` is set to the first defined view type here:
https://github.com/ClickerMonkey/dayspan-vuetify/blob/22c86947be197ad34e0cae4f03b70f206242ab4c/src/components/CalendarApp.vue#L326
but CalendarApp actually renders the 3rd view:
https://github.com/ClickerMonkey/dayspan-vuetify/blob/22c86947be197ad34e0cae4f03b70f206242ab4c/src/components/CalendarApp.vue#L450

This results in the view-selector menu displaying the incorrect view as the current view on initial load

If I set currentType explicitly (or change L326 to select the 3rd type as well) this problem does not occur.

**Comment by WolfgangAl** [comment]
Scratch that.... The actual problem is that when you initialize the DaySpan Calendar as `dayspan.months()` it defaults to a month view (which would be expected) and THAT causes the discrepancy between `currentType` and the rendered view. `rebuild` is never called on initial draw.

**Comment by ClickerMonkey** [comment]
Thanks for all your work on this, I'm going to refactor how currentType works... I never liked it.

**Comment by mtx-z** [comment]
I see this has already been updated in code (computed `currentType` code). 
I'm trying to set the default onload type (depending vuetifiy breakpoints). 

I'm able to change the type in the `created()` component method. But I'm not able to really set the default type for first calendar rendering. 

I tried this in the dsCalendarApp props:

```
calendar:
                    {
                        type: Units.DAY,
                        size: 1,
                        default() {
                            return Calendar.forType(Units.DAY, 1);
                        }
                    },
```
To match an existing `this.types` but I always get `types[1]` (week view) as default. 

I also tried to edit the computed `currentType` : 

```
 currentType:
                    {
                        get() {
                            console.log('shou', this.calendar.type)
                            return this.types.find((type) =>
                                type.type === this.calendar.type &&
                                type.size === this.calendar.size
                            ) || myCustomLogicThatReturnATypeObject;
                        },
                        set(type) {
                            this.rebuild(undefined, true, type);
                        }
                    },

```

But the first validation block is always true. And my default is never used. I'm not able to find where is the real default value used. 

Thanks !
