### ISSUE TITLE
Click on day link always goes to 'today'

### ISSUE THREAD

**Issue by WolfgangAl** [ClickerMonkey/dayspan-vuetify#72]
If I click on a day-link in any view this almost always takes me to 'today' in Day view.

But if I add an extra (since setState already does this)
```Javascript
this.calendar.set(state)
```
after
https://github.com/ClickerMonkey/dayspan-vuetify/blob/22c86947be197ad34e0cae4f03b70f206242ab4c/src/components/CalendarApp.vue#L470
it works as expected and day links always go to that day (instead of 'today')

**Comment by ClickerMonkey** [comment]
Thanks for catching this, I thought I fixed this problem already!
