### ISSUE TITLE
Multiple events on a single day overlapping on first load

### ISSUE THREAD

**Issue by developernaren** [ClickerMonkey/dayspan-vuetify#74]
I am displaying multiple events in a single day but they are overlapping on first load. It works when I change the mode to year( or any other mode) and back to month again. 

This is all I have done to load events onto the calendar

```
let state = {
    events: events
};
this.calendar.set(state);
```

**Comment by developernaren** [comment]
Calculation of `top` on `.ds-calendar-event-menu .ds-calendar-event` seems a little off on the first load and it seem to fix it if  change the mode. Can you please help me with this?

**Comment by pwnz22** [comment]
Im also having this trouble. Can you provide a fix?

**Comment by With0utFace** [comment]
> I am displaying multiple events in a single day but they are overlapping on first load. It works when I change the mode to year( or any other mode) and back to month again.
> 
> This is all I have done to load events onto the calendar
> 
> ```
> let state = {
>     events: events
> };
> this.calendar.set(state);
> ```

Hello, can you please tell me how you realized multiple events on a single day ?
