### ISSUE TITLE
Effecient way to load events

### ISSUE THREAD

**Issue by developernaren** [ClickerMonkey/dayspan-vuetify#76]
On prev and next, I am adding events to calendar. There are around 60-70 events per month. Adding events one by one in loop like this
```
this.calendar.addEvent(event)
```

takes a long time and hangs the browser. 

Adding events all at once with this code
```
this.calendar.addEvents(events)
```
is better but it still hangs the browser for few seconds. I was trying to use the progress bar to wait for the load. event the progress bar stops for few seconds, while the events load.

Is there a more efficient way to load events?

**Comment by ClickerMonkey** [comment]
I found a few improvements that could be made. Would a "setEvents" make more sense in your use case? Adding that function could also improve performance.

There are some things updated after each event is added - that should be delayed after all events are added. Vue watches some of those things so it probably triggers some unnecessary calls.

**Comment by developernaren** [comment]
I do not find a `setEvents` function in calendar. Do you mean adding a new function? It would be great if you can make improvements to this. Please let me know if I can help in any way.

**Comment by developernaren** [comment]
@ClickerMonkey any update on this?

**Comment by ClickerMonkey** [comment]
Yes, I should have an update to dayspan shortly.

**Comment by developernaren** [comment]
@ClickerMonkey BTW congratulations on officially being on Vuetify itself.

**Comment by ClickerMonkey** [comment]
@developernaren dayspan 0.12.4 published, setEvents added to Calendar which should improve performance in your scenario. Let me know how it goes.

**Comment by developernaren** [comment]
It is much better but there are still some lags.

There is an issue with next and prev buttons. If I use the prev and next button more than twice, Events stop loading completely and just the blank calendar appears.

**Comment by developernaren** [comment]
It is much better, but there is still a bit of glitchiness and still the loader is not smooth.

**Comment by deep0410** [comment]
Any update on this? 
I am using setEvents to set the events. but I am realizing for around 400 events in a month. it is taking about 8 seconds. is there a way this could be sped up?
@ClickerMonkey

**Comment by ClickerMonkey** [comment]
Kind of. I created a `v-calendar` component in Vuetify (1.5.0) which should improve some performance issues experienced by many people. I'm waiting until I create the `v-event-calendar` component in Vuetify until this library will be updated to utilize it and it's better performance and features.

**Comment by ivanvorona** [comment]
Hello @ClickerMonkey  ,  Can we expect the same functionality to be moved into Vuetify v-calendar as you built in dayspan-vuetify? or it's not on roadmap? i saw the comment somewhere on vuetify that drug&drop and other features are out of scope for v-calendar component, but looks like something is happening there.
