### ISSUE TITLE
Make calendar read-only

### ISSUE THREAD

**Issue by anoadragon453** [ClickerMonkey/dayspan-vuetify#78]
I'd like to use the calendar purely for display for some users, and editable for others. The ability to set the calendar as read-only for not logged-in users would be very useful.

Is there a way to do this already?

**Comment by ClickerMonkey** [comment]
There is not.

I plan on adding a flag `this.$dayspan.readOnly` which overrides any `read-only` attributes specified on components.

**Comment by anoadragon453** [comment]
Ideally it could hide the event creation floating action button and prevent the event creation popup from appearing?

**Comment by ClickerMonkey** [comment]
Yes - this will be in release 0.3.0 which will come out shortly.
