### ISSUE TITLE
instead of LocalStore need API to store events to table 

### ISSUE THREAD

**Issue by bebekar** [ClickerMonkey/dayspan-vuetify#81]
Events populated on the calendar use the Local store. To facilitate multiple users, need to be able to store to a database table in real-time. 
Could add additional keys such as user_id and topic_id

**Comment by ClickerMonkey** [comment]
That's just the example - as explained here you just need to listen for events to know when to call create/update/remove to your API.

https://github.com/ClickerMonkey/dayspan-vuetify/issues/42
