### ISSUE TITLE
Documentation for calendar embedded in app

### ISSUE THREAD

**Issue by lucafaggianelli** [ClickerMonkey/dayspan-vuetify#83]
Any documentation, guide or hint on how to embed a calendar inside an existing app? I see that your example app rebuild the entire layout (ds-calendar-app instantiate toolbar, drawers, etc., whereas I already have them), which is the base element that I should add in my existing app?

**Comment by ClickerMonkey** [comment]
ds-calendar

Checkout the CalendarApp component in the source to see how it's used.

**Comment by qdpy** [comment]
It is really hard to use it without -app. Can you add explanations or documentation about this type of integration? Same as @lucafaggianelli 
#59 got the same problem.
Thanks ClickerMonkey!

**Comment by lucafaggianelli** [comment]
At the end I managed to make it working, starting from ds-calendar-app and the example app, but I couldn't port all the funcionalities and I can't move forth in the implementation, I was obliged to drop this library in favor of more documented ones... what a pity! it seemed so cool and promising!

@ClickerMonkey thanks for the great lib... but do you plan any documentation?

**Comment by qdpy** [comment]
@lucafaggianelli Seems interesting. You were using ds-calendar-app component with deletions of toolbar and drawer ?

**Comment by lucafaggianelli** [comment]
Exactly! I just copy-pasted everything and removed the layout elements, the problem is that most of the sub-components of ds-calendar-app are in its slots so you have to take them out and bind some properties. I can send you some snippets with working parts, but I can't make everything working

**Comment by lucafaggianelli** [comment]
here the file component, not everything is working, I abandoned it...
https://gist.github.com/lucafaggianelli/634bd129d726f9d7410e2480897bb931

**Comment by qdpy** [comment]
Pretty nice, thanks a lot luca. Hope @ClickerMonkey will do something for us. 👍

**Comment by jonathankeebler** [comment]
@lucafaggianelli I think I got a little further down this path of creating a component with https://gist.github.com/jonathankeebler/96a58571464c02866d9d53eb0f8403f3 . I managed to remove the drawer and everything still works. I'll post an update again if I get it fully working.

**Comment by qdpy** [comment]
@jonathankeebler Did you replace "this.$dsDefaults()." it tolds me that it is undefined ?

**Comment by bupaev** [comment]
>  I was obliged to drop this library in favor of more documented ones... 
@lucafaggianelli Could you please give an example more documented libraries?

**Comment by lucafaggianelli** [comment]
I'm using https://github.com/richardtallent/vue-simple-calendar
