### ISSUE TITLE
Add Day.js compatibility

### ISSUE THREAD

**Issue by naulacambra** [ClickerMonkey/dayspan-vuetify#85]
Trying to use this package at my project, I've found several issues which I couldn't fix, until I've realized that this library depends on moment.js package (what it's not informed properly in the documentation). For performance purposes, I use [Day.js](https://github.com/iamkun/dayjs) package instead of [moment.js](https://github.com/moment/moment/).

The issues can be easliy checked using the example project [dayspan-vuetify-example](https://github.com/ClickerMonkey/dayspan-vuetify-example) and changing few things

- Install Day.js packge
`npm i --save dayjs`
- Create `vue.config.js` file to be loaded by `vue-cli-service`
```javascript
// vue.config.js
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        moment: "dayjs"
      }
    }
  }
};
```
This overrides underlying webpack configuration, to load Day.js package instead of moment.js when is imported.

After this changes, starting the project starts displaying the issues
- `npm run serve`

```
// Chrome console error
dayspan-vuetify.min.js?2f98:1 Uncaught TypeError: s.weekdaysShort is not a function
    at Object.eval (dayspan-vuetify.min.js?2f98:1)
    at t (dayspan-vuetify.min.js?2f98:1)
    at Object.eval (dayspan-vuetify.min.js?2f98:1)
    at t (dayspan-vuetify.min.js?2f98:1)
    at Object.eval (dayspan-vuetify.min.js?2f98:1)
    at t (dayspan-vuetify.min.js?2f98:1)
    at Object.eval (dayspan-vuetify.min.js?2f98:1)
    at t (dayspan-vuetify.min.js?2f98:1)
    at eval (dayspan-vuetify.min.js?2f98:1)
    at eval (dayspan-vuetify.min.js?2f98:1)
```

Even trying to override dayspan-vuetify configuration...
``` javascript
// main.js
...
Vue.use(DaySpanVuetify, {
  methods: {
    getDefaultEventColor: () => '#1976d2'
  },
  data: {
    defaults: {
      dsWeeksView: {
        weekdays: () => "dg._dl._dm._dc._dj._dv._ds.".split("_")
      }
    }
  }
});
...
```
... the same error is still displayed

Day.js [accepts plugins](https://github.com/iamkun/dayjs/blob/master/docs/en/Plugin.md) to extend its functionality.

- Create `dayjs.plugin.js` file with the methods to be added
``` javascript
// dayjs.plugin.js
export default (option, dayjsClass, dayjsFactory) => {
  // extend dayjs
  dayjsFactory.weekdaysShort = () => "dg._dl._dm._dc._dj._dv._ds.".split("_");
};
```
- Extend Day.js capabilities
``` javascript
...
import moment from 'moment'; // Mind that even we're import "moment" we're actually import "dayjs"
import plugin from './dayjs.plugin'; // Import plugin
moment.extend(plugin); // Extend "dayjs"

import DaySpanVuetify from 'dayspan-vuetify'
```
Even so, the same error is still displayed. This is because, just when dayspan-vuetify is loaded, it tries to load default values, and those leans on moment.

``` javascript
// src/defaults.js
...
import * as moment from 'moment';
...
dsWeeksView: {
    weekdays: moment.weekdaysShort()
},
...
```

My suggestion would be to let the user decide upon if he wants to use `momentjs` or `dayjs`.

**Comment by ClickerMonkey** [comment]
dayspan is the underlying library mainly using momentjs - originally I was using the plain Date object but had a few corner cases were it was broken. I'll add an enhancement issue to dayspan to remove momentjs as a dependency (or make it plugable)

**Comment by naulacambra** [comment]
Right after writing my previous comment, I figured out about the `dayspan` library.

I think Moment.js is a great library, and depend on it is fine. But the documentation should warn about it, both this library and `dayspan`.

I've forked `dayspan` to create a `dayjs` clone. I'll work on that for a few weeks, but I'll let you know whenever is functional, so you can take profit out of it, if you want.

BTW, great libraries :)

**Comment by ClickerMonkey** [comment]
Thanks! I will close this issue for now, once dayspan is changed to exclude moment (or make it pluggable) this project will be updated. I'm going to create an enhancement ticket for this project about removing the moment dependency.
