### ISSUE TITLE
Can I change the language ?

### ISSUE THREAD

**Issue by QuentinMichinot** [ClickerMonkey/dayspan-vuetify#87]
Hi,

First of all good work !

I need to change the language, can I do somethings for turn your app into french for example ?

Regards,
QM

**Comment by naulacambra** [comment]
Take a look at #54

**Comment by QuentinMichinot** [comment]
Thanks a lot !

**Comment by ClickerMonkey** [comment]
Thanks @QuentinMichinot

**Comment by ClickerMonkey** [comment]
Just a heads up - locale support is in the latest commit and will be in the next release (soon):

https://github.com/ClickerMonkey/dayspan-vuetify/commit/ec63896aadb4a889cef981091ab55998b7c0fc8f

**Comment by ClickerMonkey** [comment]
@QuentinMichinot If you are willing, all you need to do is provide a file like [this one](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/locales/en.js) and I can incorporate it into the project or add a new project so people can install the locale if they want to.

**Comment by QuentinMichinot** [comment]
@ClickerMonkey I seen you have forked me the project, I create a new branch and push it with the file ? 

It's my first one :)
