### ISSUE TITLE
Week view column headers

### ISSUE THREAD

**Issue by JerichoCross** [ClickerMonkey/dayspan-vuetify#88]
On the demo sample the week and 4-day views have a problem with the column headers not lining up properly when the main body has a vertical scroll-bar. Has this been fixed in the released code?

**Comment by ClickerMonkey** [comment]
Yes, the fix went out with the last release. I haven't updated the example yet, thank you for noticing.

**Comment by JerichoCross** [comment]
No problem. It's a great component!
