### ISSUE TITLE
Add catalan localization file

### ISSUE THREAD

**Issue by naulacambra** [ClickerMonkey/dayspan-vuetify#90]
I'm adding a catalan file for localization (I'll add the spanish also), but I've a question.

I'm not an really used to enlgish, so I don't know if there's any way to determine the formality of the english localization (I'm not sure if this makes sense)

In catalan or spanish (and I'm sure, a lot more languages) there are various ways to address yourself to another person, one is more formal (and more respectful) than the other. But as far I know, in english both ways are written the same.

| Language | Informal form | Formal form | |
|:-------------:|:-------------|:-----|--|
| English | I have a pen for **you** | I have a pen for **you** | Same |
| Catalan | Tinc un bolígraf per **tu** | Tinc un bolígraf per **vosté** | Not the same |
| Spanish | Tengo un bolígrafo para **ti** | Tengo un bolígrafo para **usted** | Not the same |

My question is: which form should use for the localizations?

Mind that Google Calendar uses the informal form.

**Comment by naulacambra** [comment]
Since the library is emulating google calendar style, I think we should stick to the informal form as well.

I can't came up with any good reason to use the formal form. Even though, we can change it in the future with almost 0 effort.

**Comment by ClickerMonkey** [comment]
Is this something you are still working on?

**Comment by naulacambra** [comment]
It's done, check #114 . Sorry about the delay
