### ISSUE TITLE
Add possibility to disable toolbar and drawer on CalendarApp

### ISSUE THREAD

**Issue by ThiagoAugustoSM** [ClickerMonkey/dayspan-vuetify#93]
Currently in the component [CalendarApp](https://github.com/ClickerMonkey/dayspan-vuetify/blob/master/src/components/CalendarApp.vue) the navigation-drawer and toolbar are hardcode on the code. 
It would be good to have the possibility to disable those from the parent.

**Comment by ClickerMonkey** [comment]
That's why you use the ds-calendar component.
