### ISSUE TITLE
How can I change the default event behavior ?

### ISSUE THREAD

**Issue by azy777** [ClickerMonkey/dayspan-vuetify#95]
Hi - I need to be able to change the default template which is fired on events. Say for example, for the slot eventPopover, I want to load my own modal popup with custom form and styling instead of the default behavior. Can you let me know what would be the best way to achieve this? . Thanks.

**Comment by mtx-z** [comment]
Hello, I'm trying the exact same thing. 

I want to open a custom modal on event click, and so prevent the default one to open.

I added listener to my main componenent on `mouse-down-event` and `open`. Both on a simple method that console.log the event object, and set the `handled` parameter.

```
test(event){
                console.log(event);
                event.handled = true;
            },
```

I see the console.log(), so the listener is working. But the default modal still opens. I believe my listener is trigger after the default component or child-component listeners that open the default modal. I also didn't see any overrideable method that handle the event click event. 

Is there something I'm missing? In the end, I just want to use the calendar as display, and use my own components and logic to handle the rest (create, update, delete, event detail etc...).

Thanks !

**Comment by ClickerMonkey** [comment]
Looks like the edit event is the one that opens the event dialog, since you have `ref="app"` you could do `this.$refs.app.edit = () => {}` in that component.

It's a hack until I think of a more consistent way to handle overriding this sort of stuff

**Comment by mtx-z** [comment]
Hey, thanks for the heads up. 
In the end, I found the `@edit="edit"` in the CalendarApp on the `ds-agenda`, so I can handle from here. 
Thanks !
